/* tag_relocate.c

Cache files are linked to the Xbox tag cache address (0x803A6000): tag data
and structure BSPs hold absolute pointers into that 22 MB window. A process
that cannot map the window there (the Vita) loads the data wherever its tag
cache is and adds the difference to every pointer.

Which words are pointers comes from the tag definitions (tag_layouts.h,
generated by tools/gen_tag_layouts.py from Invader's): the walk starts at
the tag index and the BSP header and follows every block, as the game does,
relocating block, data and tag reference pointers and the Xbox-only raw
pointers (model parts, BSP materials). A scan by value would not do: packed
vertex normals and collision BSP indices look like window addresses.

HALO_TAG_RELOCATION_REPORT=1 prints what was relocated; HALO_TAG_DUMP=<dir>
keeps a copy of what was read, before relocation. */

#include <stdio.h>
#include <stdlib.h>

/* (platform.h's; stderr on Linux, the log on the Vita) */
void platform_log(const char *format, ...);
#include <string.h>

#include "tag_relocate.h"

#define XBOX_TAG_CACHE_BASE 0x803A6000UL
#define XBOX_TAG_CACHE_SIZE 0x01600000UL
#define WINDOW_WORDS (XBOX_TAG_CACHE_SIZE / 4)

enum
{
	_tag_field_block,
	_tag_field_data,
	_tag_field_reference,
	_tag_field_pointer,
	_tag_field_struct
};

struct tag_layout_field
{
	unsigned short offset;
	unsigned char kind;
	/* the element or embedded struct (0xFFFF: one without pointers), and
	a block element's size */
	unsigned short child;
	unsigned long child_size;
};

struct tag_layout_struct
{
	unsigned short first_field;
	unsigned short field_count;
};

struct tag_layout_group
{
	unsigned long group_tag;
	unsigned short root;
};

#include "tag_layouts.h"

#define NO_LAYOUT 0xFFFF

static struct
{
	unsigned char *window;
	unsigned long bias;
	/* one bit per word of the window: relocated already */
	unsigned char relocated[WINDOW_WORDS / 8];
	/* the loaded ranges, as Xbox addresses; pointers are followed only
	into them */
	unsigned long tags_end;
	unsigned long bsp_start, bsp_end;
	unsigned long pointers, outside, walked;
	int report;
} relocation;

static int loaded(unsigned long xbox_address)
{
	return (xbox_address >= XBOX_TAG_CACHE_BASE && xbox_address < relocation.tags_end) ||
		(xbox_address >= relocation.bsp_start && xbox_address < relocation.bsp_end);
}

/* relocates the pointer at location (inside the window) once; returns where
it points in this process, or NULL when it does not point into the window */
static unsigned char *relocate_word(unsigned char *location)
{
	unsigned long word = (unsigned long)(location - relocation.window) / 4;
	unsigned long value;

	if (word >= WINDOW_WORDS)
		return NULL;
	memcpy(&value, location, 4);
	if (relocation.relocated[word / 8] & (1 << (word % 8)))
		return (unsigned char *)value;
	if (value - XBOX_TAG_CACHE_BASE >= XBOX_TAG_CACHE_SIZE)
	{
		if (value)
			relocation.outside++;
		return NULL;
	}
	relocation.relocated[word / 8] |= (unsigned char)(1 << (word % 8));
	relocation.pointers++;
	value += relocation.bias;
	memcpy(location, &value, 4);
	return (unsigned char *)value;
}

static void walk(unsigned short struct_index, unsigned char *address)
{
	const struct tag_layout_struct *layout = &tag_layout_structs[struct_index];
	unsigned short index;

	relocation.walked++;
	for (index = 0; index < layout->field_count; index++)
	{
		const struct tag_layout_field *field = &tag_layout_fields[layout->first_field + index];
		unsigned char *at = address + field->offset;

		switch (field->kind)
		{
		case _tag_field_block:
		{
			long count;
			unsigned char *elements;

			memcpy(&count, at, 4);
			elements = relocate_word(at + 4);
			if (elements && count > 0 && field->child != NO_LAYOUT &&
				loaded((unsigned long)(elements - relocation.bias)))
			{
				long element;

				for (element = 0; element < count; element++)
					walk(field->child, elements + element * field->child_size);
			}
			break;
		}
		case _tag_field_data:
			relocate_word(at + 12);
			break;
		case _tag_field_reference:
			relocate_word(at + 4);
			break;
		case _tag_field_pointer:
			relocate_word(at);
			break;
		case _tag_field_struct:
			if (field->child != NO_LAYOUT)
				walk(field->child, at);
			break;
		}
	}
}

/* the vertex or index buffer headers of an array: D3DResource Common,
Data (a pointer), Lock */
static void relocate_buffers(unsigned char *array, long count)
{
	long index;

	if (!array || count <= 0 || !loaded((unsigned long)(array - relocation.bias)))
		return;
	for (index = 0; index < count; index++)
		relocate_word(array + index * 12 + 4);
}

static void dump(void *data, unsigned long size, const char *name)
{
	const char *directory = getenv("HALO_TAG_DUMP");
	static int dump_index;
	char path[512];
	FILE *file;
	unsigned long xbox_address = (unsigned long)data - relocation.bias;

	if (!directory)
		return;
	snprintf(path, sizeof(path), "%s/%02d-%s.bin", directory, dump_index++, name);
	file = fopen(path, "wb");
	if (file)
	{
		fwrite(&xbox_address, 4, 1, file);
		fwrite(data, 1, size, file);
		fclose(file);
	}
}

static void begin(void *tag_cache)
{
	const char *value = getenv("HALO_TAG_RELOCATION_REPORT");

	relocation.report = value && value[0] == '1';
	relocation.window = tag_cache;
	relocation.bias = (unsigned long)tag_cache - XBOX_TAG_CACHE_BASE;
	relocation.pointers = relocation.outside = relocation.walked = 0;
}

static void finish(const char *what, unsigned long size)
{
	if (relocation.report)
		platform_log("tag-relocate: %s: %lu bytes, bias 0x%08lx: %lu pointers relocated, %lu structs walked, "
			"%lu pointer fields outside the window", what, size, relocation.bias, relocation.pointers,
			relocation.walked, relocation.outside);
}

void halo_tag_relocate_tags(void *tag_cache, unsigned long size)
{
	unsigned char *header = tag_cache;
	unsigned char *instances;
	long count, index, vertex_buffer_count, index_buffer_count;

	begin(tag_cache);
	dump(tag_cache, size, "tags");
	memset(relocation.relocated, 0, sizeof(relocation.relocated));
	relocation.tags_end = XBOX_TAG_CACHE_BASE + size;
	relocation.bsp_start = relocation.bsp_end = 0;
	if (!relocation.bias)
		return;
	/* the header: tag instances, count, vertex and index buffers */
	instances = relocate_word(header);
	memcpy(&count, header + 12, 4);
	memcpy(&vertex_buffer_count, header + 16, 4);
	memcpy(&index_buffer_count, header + 24, 4);
	relocate_buffers(relocate_word(header + 20), vertex_buffer_count);
	relocate_buffers(relocate_word(header + 28), index_buffer_count);
	if (!instances)
		return;
	for (index = 0; index < count; index++)
	{
		/* group tags x3, tag index, name, base address, unused x2 */
		unsigned char *instance = instances + index * 32;
		unsigned long group_tag;
		unsigned char *base;
		unsigned short group;

		relocate_word(instance + 16);
		base = relocate_word(instance + 20);
		if (!base || !loaded((unsigned long)(base - relocation.bias)))
			continue;
		memcpy(&group_tag, instance, 4);
		for (group = 0; group < sizeof(tag_layout_groups) / sizeof(tag_layout_groups[0]); group++)
		{
			if (tag_layout_groups[group].group_tag == group_tag)
			{
				if (tag_layout_groups[group].root != NO_LAYOUT)
					walk(tag_layout_groups[group].root, base);
				break;
			}
		}
		if (group == sizeof(tag_layout_groups) / sizeof(tag_layout_groups[0]))
			platform_log("tag-relocate: no layout for tag group '%c%c%c%c'",
				(int)(group_tag >> 24), (int)(group_tag >> 16 & 0xff), (int)(group_tag >> 8 & 0xff), (int)(group_tag & 0xff));
	}
	finish("tags", size);
}

void halo_tag_relocate_structure_bsp(void *tag_cache, void *bsp, unsigned long size)
{
	unsigned char *header = bsp;
	unsigned char *structure;
	unsigned long start_word, end_word, word;
	long vertex_buffer_count, lightmap_vertex_buffer_count;

	begin(tag_cache);
	dump(bsp, size, "bsp");
	relocation.bsp_start = (unsigned long)bsp - relocation.bias;
	relocation.bsp_end = relocation.bsp_start + size;
	if (!relocation.bias)
		return;
	/* this BSP replaces whatever was loaded there before */
	start_word = (unsigned long)(header - relocation.window) / 4;
	end_word = start_word + (size + 3) / 4;
	if (end_word > WINDOW_WORDS)
		end_word = WINDOW_WORDS;
	for (word = start_word; word < end_word; word++)
		relocation.relocated[word / 8] &= (unsigned char)~(1 << (word % 8));
	/* the header: the BSP tag, vertex buffers, lightmap vertex buffers */
	structure = relocate_word(header);
	memcpy(&vertex_buffer_count, header + 4, 4);
	memcpy(&lightmap_vertex_buffer_count, header + 12, 4);
	relocate_buffers(relocate_word(header + 8), vertex_buffer_count);
	relocate_buffers(relocate_word(header + 16), lightmap_vertex_buffer_count);
	if (structure && loaded((unsigned long)(structure - relocation.bias)))
		walk(TAG_LAYOUT_STRUCTURE_BSP, structure);
	finish("structure bsp", size);
}
