/* tag_layouts.h: generated by tools/gen_tag_layouts.py from Invader's tag definitions; do not edit */

static const struct tag_layout_field tag_layout_fields[] = {
	{ 56, _tag_field_reference, 65535, 0 }, /* UIWidgetDefinition */
	{ 72, _tag_field_block, 65535, 36 }, /* UIWidgetDefinition */
	{ 84, _tag_field_block, 1, 72 }, /* UIWidgetDefinition */
	{ 96, _tag_field_block, 65535, 34 }, /* UIWidgetDefinition */
	{ 236, _tag_field_reference, 65535, 0 }, /* UIWidgetDefinition */
	{ 252, _tag_field_reference, 65535, 0 }, /* UIWidgetDefinition */
	{ 340, _tag_field_reference, 65535, 0 }, /* UIWidgetDefinition */
	{ 356, _tag_field_reference, 65535, 0 }, /* UIWidgetDefinition */
	{ 420, _tag_field_reference, 65535, 0 }, /* UIWidgetDefinition */
	{ 724, _tag_field_block, 2, 80 }, /* UIWidgetDefinition */
	{ 992, _tag_field_block, 3, 80 }, /* UIWidgetDefinition */
	{ 8, _tag_field_reference, 65535, 0 }, /* EventHandlerReference */
	{ 24, _tag_field_reference, 65535, 0 }, /* EventHandlerReference */
	{ 0, _tag_field_reference, 65535, 0 }, /* ConditionalWidgetReference */
	{ 0, _tag_field_reference, 65535, 0 }, /* ChildWidgetReference */
	{ 0, _tag_field_block, 5, 16 }, /* UIWidgetCollection */
	{ 0, _tag_field_reference, 65535, 0 }, /* UIWidgetCollectionReference */
	{ 316, _tag_field_reference, 65535, 0 }, /* Actor */
	{ 600, _tag_field_reference, 65535, 0 }, /* Actor */
	{ 1208, _tag_field_reference, 65535, 0 }, /* Actor */
	{ 4, _tag_field_reference, 65535, 0 }, /* ActorVariant */
	{ 20, _tag_field_reference, 65535, 0 }, /* ActorVariant */
	{ 36, _tag_field_reference, 65535, 0 }, /* ActorVariant */
	{ 100, _tag_field_reference, 65535, 0 }, /* ActorVariant */
	{ 448, _tag_field_reference, 65535, 0 }, /* ActorVariant */
	{ 556, _tag_field_block, 65535, 32 }, /* ActorVariant */
	{ 32, _tag_field_reference, 65535, 0 }, /* Antenna */
	{ 48, _tag_field_reference, 65535, 0 }, /* Antenna */
	{ 196, _tag_field_block, 65535, 128 }, /* Antenna */
	{ 0, _tag_field_block, 65535, 20 }, /* ModelAnimations */
	{ 12, _tag_field_block, 10, 100 }, /* ModelAnimations */
	{ 24, _tag_field_block, 13, 28 }, /* ModelAnimations */
	{ 36, _tag_field_block, 14, 116 }, /* ModelAnimations */
	{ 48, _tag_field_block, 15, 96 }, /* ModelAnimations */
	{ 60, _tag_field_block, 65535, 2 }, /* ModelAnimations */
	{ 72, _tag_field_block, 16, 28 }, /* ModelAnimations */
	{ 84, _tag_field_block, 17, 20 }, /* ModelAnimations */
	{ 104, _tag_field_block, 65535, 64 }, /* ModelAnimations */
	{ 116, _tag_field_block, 18, 180 }, /* ModelAnimations */
	{ 64, _tag_field_block, 65535, 2 }, /* ModelAnimationsAnimationGraphUnitSeat */
	{ 76, _tag_field_block, 65535, 64 }, /* ModelAnimationsAnimationGraphUnitSeat */
	{ 88, _tag_field_block, 11, 188 }, /* ModelAnimationsAnimationGraphUnitSeat */
	{ 152, _tag_field_block, 65535, 2 }, /* ModelAnimationsAnimationGraphWeapon */
	{ 164, _tag_field_block, 65535, 64 }, /* ModelAnimationsAnimationGraphWeapon */
	{ 176, _tag_field_block, 12, 60 }, /* ModelAnimationsAnimationGraphWeapon */
	{ 48, _tag_field_block, 65535, 2 }, /* ModelAnimationsAnimationGraphWeaponType */
	{ 16, _tag_field_block, 65535, 2 }, /* ModelAnimationsAnimationGraphWeaponAnimations */
	{ 92, _tag_field_block, 65535, 2 }, /* ModelAnimationsAnimationGraphVehicleAnimations */
	{ 104, _tag_field_block, 65535, 20 }, /* ModelAnimationsAnimationGraphVehicleAnimations */
	{ 84, _tag_field_block, 65535, 2 }, /* ModelAnimationsDeviceAnimations */
	{ 16, _tag_field_block, 65535, 2 }, /* ModelAnimationsAnimationGraphFirstPersonWeaponAnimations */
	{ 0, _tag_field_reference, 65535, 0 }, /* ModelAnimationsAnimationGraphSoundReference */
	{ 72, _tag_field_data, 65535, 0 }, /* ModelAnimationsAnimation */
	{ 140, _tag_field_data, 65535, 0 }, /* ModelAnimationsAnimation */
	{ 160, _tag_field_data, 65535, 0 }, /* ModelAnimationsAnimation */
	{ 40, _tag_field_reference, 65535, 0 }, /* Biped */
	{ 56, _tag_field_reference, 65535, 0 }, /* Biped */
	{ 112, _tag_field_reference, 65535, 0 }, /* Biped */
	{ 128, _tag_field_reference, 65535, 0 }, /* Biped */
	{ 144, _tag_field_reference, 65535, 0 }, /* Biped */
	{ 160, _tag_field_reference, 65535, 0 }, /* Biped */
	{ 320, _tag_field_block, 20, 72 }, /* Biped */
	{ 332, _tag_field_block, 21, 32 }, /* Biped */
	{ 344, _tag_field_block, 65535, 360 }, /* Biped */
	{ 356, _tag_field_block, 22, 44 }, /* Biped */
	{ 368, _tag_field_block, 65535, 8 }, /* Biped */
	{ 392, _tag_field_reference, 65535, 0 }, /* Biped */
	{ 500, _tag_field_block, 23, 28 }, /* Biped */
	{ 588, _tag_field_reference, 65535, 0 }, /* Biped */
	{ 648, _tag_field_reference, 65535, 0 }, /* Biped */
	{ 680, _tag_field_block, 24, 48 }, /* Biped */
	{ 692, _tag_field_block, 25, 24 }, /* Biped */
	{ 716, _tag_field_block, 65535, 68 }, /* Biped */
	{ 728, _tag_field_block, 26, 36 }, /* Biped */
	{ 740, _tag_field_block, 27, 284 }, /* Biped */
	{ 788, _tag_field_reference, 65535, 0 }, /* Biped */
	{ 908, _tag_field_reference, 65535, 0 }, /* Biped */
	{ 1256, _tag_field_block, 65535, 64 }, /* Biped */
	{ 0, _tag_field_reference, 65535, 0 }, /* ObjectAttachment */
	{ 0, _tag_field_reference, 65535, 0 }, /* ObjectWidget */
	{ 32, _tag_field_block, 65535, 28 }, /* ObjectChangeColors */
	{ 0, _tag_field_reference, 65535, 0 }, /* UnitCameraTrack */
	{ 0, _tag_field_reference, 65535, 0 }, /* UnitUnitHudInterface */
	{ 8, _tag_field_reference, 65535, 0 }, /* UnitDialogueVariant */
	{ 0, _tag_field_reference, 65535, 0 }, /* UnitWeapon */
	{ 208, _tag_field_block, 23, 28 }, /* UnitSeat */
	{ 220, _tag_field_block, 24, 48 }, /* UnitSeat */
	{ 248, _tag_field_reference, 65535, 0 }, /* UnitSeat */
	{ 28, _tag_field_data, 65535, 0 }, /* Bitmap */
	{ 48, _tag_field_data, 65535, 0 }, /* Bitmap */
	{ 84, _tag_field_block, 29, 64 }, /* Bitmap */
	{ 96, _tag_field_block, 30, 48 }, /* Bitmap */
	{ 52, _tag_field_block, 65535, 32 }, /* BitmapGroupSequence */
	{ 36, _tag_field_pointer, 65535, 0 }, /* BitmapData */
	{ 112, _tag_field_reference, 65535, 0 }, /* ModelCollisionGeometry */
	{ 132, _tag_field_reference, 65535, 0 }, /* ModelCollisionGeometry */
	{ 152, _tag_field_reference, 65535, 0 }, /* ModelCollisionGeometry */
	{ 168, _tag_field_reference, 65535, 0 }, /* ModelCollisionGeometry */
	{ 188, _tag_field_reference, 65535, 0 }, /* ModelCollisionGeometry */
	{ 392, _tag_field_reference, 65535, 0 }, /* ModelCollisionGeometry */
	{ 408, _tag_field_reference, 65535, 0 }, /* ModelCollisionGeometry */
	{ 424, _tag_field_reference, 65535, 0 }, /* ModelCollisionGeometry */
	{ 564, _tag_field_block, 65535, 72 }, /* ModelCollisionGeometry */
	{ 576, _tag_field_block, 32, 84 }, /* ModelCollisionGeometry */
	{ 588, _tag_field_block, 65535, 52 }, /* ModelCollisionGeometry */
	{ 640, _tag_field_block, 65535, 32 }, /* ModelCollisionGeometry */
	{ 652, _tag_field_block, 33, 64 }, /* ModelCollisionGeometry */
	{ 56, _tag_field_reference, 65535, 0 }, /* ModelCollisionGeometryRegion */
	{ 72, _tag_field_block, 65535, 32 }, /* ModelCollisionGeometryRegion */
	{ 52, _tag_field_block, 34, 96 }, /* ModelCollisionGeometryNode */
	{ 0, _tag_field_block, 65535, 12 }, /* ModelCollisionGeometryBSP */
	{ 12, _tag_field_block, 65535, 16 }, /* ModelCollisionGeometryBSP */
	{ 24, _tag_field_block, 65535, 8 }, /* ModelCollisionGeometryBSP */
	{ 36, _tag_field_block, 65535, 8 }, /* ModelCollisionGeometryBSP */
	{ 48, _tag_field_block, 65535, 20 }, /* ModelCollisionGeometryBSP */
	{ 60, _tag_field_block, 65535, 12 }, /* ModelCollisionGeometryBSP */
	{ 72, _tag_field_block, 65535, 24 }, /* ModelCollisionGeometryBSP */
	{ 84, _tag_field_block, 65535, 16 }, /* ModelCollisionGeometryBSP */
	{ 0, _tag_field_block, 65535, 48 }, /* ColorTable */
	{ 48, _tag_field_reference, 65535, 0 }, /* Contrail */
	{ 208, _tag_field_reference, 65535, 0 }, /* Contrail */
	{ 312, _tag_field_block, 37, 104 }, /* Contrail */
	{ 16, _tag_field_reference, 65535, 0 }, /* ContrailPointState */
	{ 40, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 56, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 112, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 128, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 144, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 160, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 320, _tag_field_block, 20, 72 }, /* DeviceControl */
	{ 332, _tag_field_block, 21, 32 }, /* DeviceControl */
	{ 344, _tag_field_block, 65535, 360 }, /* DeviceControl */
	{ 356, _tag_field_block, 22, 44 }, /* DeviceControl */
	{ 368, _tag_field_block, 65535, 8 }, /* DeviceControl */
	{ 416, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 432, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 448, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 464, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 480, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 496, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 524, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 744, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 760, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 776, _tag_field_reference, 65535, 0 }, /* DeviceControl */
	{ 8, _tag_field_reference, 65535, 0 }, /* Decal */
	{ 216, _tag_field_reference, 65535, 0 }, /* Decal */
	{ 4, _tag_field_data, 65535, 0 }, /* InputDeviceDefaults */
	{ 24, _tag_field_data, 65535, 0 }, /* InputDeviceDefaults */
	{ 40, _tag_field_reference, 65535, 0 }, /* Device */
	{ 56, _tag_field_reference, 65535, 0 }, /* Device */
	{ 112, _tag_field_reference, 65535, 0 }, /* Device */
	{ 128, _tag_field_reference, 65535, 0 }, /* Device */
	{ 144, _tag_field_reference, 65535, 0 }, /* Device */
	{ 160, _tag_field_reference, 65535, 0 }, /* Device */
	{ 320, _tag_field_block, 20, 72 }, /* Device */
	{ 332, _tag_field_block, 21, 32 }, /* Device */
	{ 344, _tag_field_block, 65535, 360 }, /* Device */
	{ 356, _tag_field_block, 22, 44 }, /* Device */
	{ 368, _tag_field_block, 65535, 8 }, /* Device */
	{ 416, _tag_field_reference, 65535, 0 }, /* Device */
	{ 432, _tag_field_reference, 65535, 0 }, /* Device */
	{ 448, _tag_field_reference, 65535, 0 }, /* Device */
	{ 464, _tag_field_reference, 65535, 0 }, /* Device */
	{ 480, _tag_field_reference, 65535, 0 }, /* Device */
	{ 496, _tag_field_reference, 65535, 0 }, /* Device */
	{ 524, _tag_field_reference, 65535, 0 }, /* Device */
	{ 52, _tag_field_reference, 65535, 0 }, /* DetailObjectCollection */
	{ 68, _tag_field_block, 65535, 96 }, /* DetailObjectCollection */
	{ 40, _tag_field_block, 65535, 32 }, /* Effect */
	{ 52, _tag_field_block, 44, 68 }, /* Effect */
	{ 44, _tag_field_block, 45, 104 }, /* EffectEvent */
	{ 56, _tag_field_block, 46, 232 }, /* EffectEvent */
	{ 24, _tag_field_reference, 65535, 0 }, /* EffectPart */
	{ 84, _tag_field_reference, 65535, 0 }, /* EffectParticle */
	{ 52, _tag_field_reference, 65535, 0 }, /* Lightning */
	{ 152, _tag_field_block, 65535, 228 }, /* Lightning */
	{ 164, _tag_field_block, 48, 180 }, /* Lightning */
	{ 76, _tag_field_reference, 65535, 0 }, /* LightningShader */
	{ 40, _tag_field_reference, 65535, 0 }, /* Equipment */
	{ 56, _tag_field_reference, 65535, 0 }, /* Equipment */
	{ 112, _tag_field_reference, 65535, 0 }, /* Equipment */
	{ 128, _tag_field_reference, 65535, 0 }, /* Equipment */
	{ 144, _tag_field_reference, 65535, 0 }, /* Equipment */
	{ 160, _tag_field_reference, 65535, 0 }, /* Equipment */
	{ 320, _tag_field_block, 20, 72 }, /* Equipment */
	{ 332, _tag_field_block, 21, 32 }, /* Equipment */
	{ 344, _tag_field_block, 65535, 360 }, /* Equipment */
	{ 356, _tag_field_block, 22, 44 }, /* Equipment */
	{ 368, _tag_field_block, 65535, 8 }, /* Equipment */
	{ 584, _tag_field_reference, 65535, 0 }, /* Equipment */
	{ 600, _tag_field_reference, 65535, 0 }, /* Equipment */
	{ 744, _tag_field_reference, 65535, 0 }, /* Equipment */
	{ 760, _tag_field_reference, 65535, 0 }, /* Equipment */
	{ 784, _tag_field_reference, 65535, 0 }, /* Equipment */
	{ 24, _tag_field_reference, 65535, 0 }, /* Flag */
	{ 40, _tag_field_reference, 65535, 0 }, /* Flag */
	{ 68, _tag_field_reference, 65535, 0 }, /* Flag */
	{ 84, _tag_field_block, 65535, 52 }, /* Flag */
	{ 188, _tag_field_reference, 65535, 0 }, /* Fog */
	{ 244, _tag_field_reference, 65535, 0 }, /* Fog */
	{ 260, _tag_field_reference, 65535, 0 }, /* Fog */
	{ 48, _tag_field_block, 53, 12 }, /* Font */
	{ 60, _tag_field_reference, 65535, 0 }, /* Font */
	{ 76, _tag_field_reference, 65535, 0 }, /* Font */
	{ 92, _tag_field_reference, 65535, 0 }, /* Font */
	{ 108, _tag_field_reference, 65535, 0 }, /* Font */
	{ 124, _tag_field_block, 65535, 20 }, /* Font */
	{ 136, _tag_field_data, 65535, 0 }, /* Font */
	{ 0, _tag_field_block, 65535, 2 }, /* FontCharacterTables */
	{ 0, _tag_field_block, 55, 28 }, /* MaterialEffects */
	{ 0, _tag_field_block, 56, 48 }, /* MaterialEffectsMaterialEffect */
	{ 0, _tag_field_reference, 65535, 0 }, /* MaterialEffectsMaterialEffectMaterial */
	{ 16, _tag_field_reference, 65535, 0 }, /* MaterialEffectsMaterialEffectMaterial */
	{ 40, _tag_field_reference, 65535, 0 }, /* Garbage */
	{ 56, _tag_field_reference, 65535, 0 }, /* Garbage */
	{ 112, _tag_field_reference, 65535, 0 }, /* Garbage */
	{ 128, _tag_field_reference, 65535, 0 }, /* Garbage */
	{ 144, _tag_field_reference, 65535, 0 }, /* Garbage */
	{ 160, _tag_field_reference, 65535, 0 }, /* Garbage */
	{ 320, _tag_field_block, 20, 72 }, /* Garbage */
	{ 332, _tag_field_block, 21, 32 }, /* Garbage */
	{ 344, _tag_field_block, 65535, 360 }, /* Garbage */
	{ 356, _tag_field_block, 22, 44 }, /* Garbage */
	{ 368, _tag_field_block, 65535, 8 }, /* Garbage */
	{ 584, _tag_field_reference, 65535, 0 }, /* Garbage */
	{ 600, _tag_field_reference, 65535, 0 }, /* Garbage */
	{ 744, _tag_field_reference, 65535, 0 }, /* Garbage */
	{ 760, _tag_field_reference, 65535, 0 }, /* Garbage */
	{ 324, _tag_field_reference, 65535, 0 }, /* Glow */
	{ 72, _tag_field_reference, 65535, 0 }, /* GrenadeHUDInterface */
	{ 124, _tag_field_block, 60, 480 }, /* GrenadeHUDInterface */
	{ 176, _tag_field_reference, 65535, 0 }, /* GrenadeHUDInterface */
	{ 228, _tag_field_block, 60, 480 }, /* GrenadeHUDInterface */
	{ 332, _tag_field_reference, 65535, 0 }, /* GrenadeHUDInterface */
	{ 348, _tag_field_block, 65535, 136 }, /* GrenadeHUDInterface */
	{ 360, _tag_field_block, 61, 56 }, /* GrenadeHUDInterface */
	{ 100, _tag_field_reference, 65535, 0 }, /* HUDInterfaceMultitextureOverlay */
	{ 116, _tag_field_reference, 65535, 0 }, /* HUDInterfaceMultitextureOverlay */
	{ 132, _tag_field_reference, 65535, 0 }, /* HUDInterfaceMultitextureOverlay */
	{ 340, _tag_field_block, 65535, 220 }, /* HUDInterfaceMultitextureOverlay */
	{ 0, _tag_field_reference, 65535, 0 }, /* GrenadeHUDInterfaceSound */
	{ 0, _tag_field_data, 65535, 0 }, /* HUDMessageText */
	{ 20, _tag_field_block, 65535, 2 }, /* HUDMessageText */
	{ 32, _tag_field_block, 65535, 64 }, /* HUDMessageText */
	{ 0, _tag_field_reference, 65535, 0 }, /* HUDNumber */
	{ 72, _tag_field_reference, 65535, 0 }, /* HUDGlobals */
	{ 88, _tag_field_reference, 65535, 0 }, /* HUDGlobals */
	{ 148, _tag_field_reference, 65535, 0 }, /* HUDGlobals */
	{ 164, _tag_field_reference, 65535, 0 }, /* HUDGlobals */
	{ 180, _tag_field_reference, 65535, 0 }, /* HUDGlobals */
	{ 196, _tag_field_block, 65535, 16 }, /* HUDGlobals */
	{ 240, _tag_field_reference, 65535, 0 }, /* HUDGlobals */
	{ 336, _tag_field_reference, 65535, 0 }, /* HUDGlobals */
	{ 352, _tag_field_block, 65535, 104 }, /* HUDGlobals */
	{ 704, _tag_field_reference, 65535, 0 }, /* HUDGlobals */
	{ 824, _tag_field_reference, 65535, 0 }, /* HUDGlobals */
	{ 968, _tag_field_reference, 65535, 0 }, /* HUDGlobals */
	{ 992, _tag_field_reference, 65535, 0 }, /* HUDGlobals */
	{ 1008, _tag_field_block, 65, 28 }, /* HUDGlobals */
	{ 0, _tag_field_reference, 65535, 0 }, /* HUDGlobalsAnniversaryRemap */
	{ 16, _tag_field_block, 66, 20 }, /* HUDGlobalsAnniversaryRemap */
	{ 0, _tag_field_reference, 65535, 0 }, /* HUDGlobalsAnniversaryRemapTarget */
	{ 40, _tag_field_reference, 65535, 0 }, /* Item */
	{ 56, _tag_field_reference, 65535, 0 }, /* Item */
	{ 112, _tag_field_reference, 65535, 0 }, /* Item */
	{ 128, _tag_field_reference, 65535, 0 }, /* Item */
	{ 144, _tag_field_reference, 65535, 0 }, /* Item */
	{ 160, _tag_field_reference, 65535, 0 }, /* Item */
	{ 320, _tag_field_block, 20, 72 }, /* Item */
	{ 332, _tag_field_block, 21, 32 }, /* Item */
	{ 344, _tag_field_block, 65535, 360 }, /* Item */
	{ 356, _tag_field_block, 22, 44 }, /* Item */
	{ 368, _tag_field_block, 65535, 8 }, /* Item */
	{ 584, _tag_field_reference, 65535, 0 }, /* Item */
	{ 600, _tag_field_reference, 65535, 0 }, /* Item */
	{ 744, _tag_field_reference, 65535, 0 }, /* Item */
	{ 760, _tag_field_reference, 65535, 0 }, /* Item */
	{ 0, _tag_field_block, 69, 84 }, /* ItemCollection */
	{ 36, _tag_field_reference, 65535, 0 }, /* ItemCollectionPermutation */
	{ 276, _tag_field_reference, 65535, 0 }, /* DamageEffect */
	{ 32, _tag_field_reference, 65535, 0 }, /* LensFlare */
	{ 196, _tag_field_block, 65535, 128 }, /* LensFlare */
	{ 40, _tag_field_reference, 65535, 0 }, /* DeviceLightFixture */
	{ 56, _tag_field_reference, 65535, 0 }, /* DeviceLightFixture */
	{ 112, _tag_field_reference, 65535, 0 }, /* DeviceLightFixture */
	{ 128, _tag_field_reference, 65535, 0 }, /* DeviceLightFixture */
	{ 144, _tag_field_reference, 65535, 0 }, /* DeviceLightFixture */
	{ 160, _tag_field_reference, 65535, 0 }, /* DeviceLightFixture */
	{ 320, _tag_field_block, 20, 72 }, /* DeviceLightFixture */
	{ 332, _tag_field_block, 21, 32 }, /* DeviceLightFixture */
	{ 344, _tag_field_block, 65535, 360 }, /* DeviceLightFixture */
	{ 356, _tag_field_block, 22, 44 }, /* DeviceLightFixture */
	{ 368, _tag_field_block, 65535, 8 }, /* DeviceLightFixture */
	{ 416, _tag_field_reference, 65535, 0 }, /* DeviceLightFixture */
	{ 432, _tag_field_reference, 65535, 0 }, /* DeviceLightFixture */
	{ 448, _tag_field_reference, 65535, 0 }, /* DeviceLightFixture */
	{ 464, _tag_field_reference, 65535, 0 }, /* DeviceLightFixture */
	{ 480, _tag_field_reference, 65535, 0 }, /* DeviceLightFixture */
	{ 496, _tag_field_reference, 65535, 0 }, /* DeviceLightFixture */
	{ 524, _tag_field_reference, 65535, 0 }, /* DeviceLightFixture */
	{ 100, _tag_field_reference, 65535, 0 }, /* Light */
	{ 124, _tag_field_reference, 65535, 0 }, /* Light */
	{ 172, _tag_field_reference, 65535, 0 }, /* Light */
	{ 44, _tag_field_reference, 65535, 0 }, /* SoundLooping */
	{ 60, _tag_field_block, 75, 160 }, /* SoundLooping */
	{ 72, _tag_field_block, 76, 104 }, /* SoundLooping */
	{ 48, _tag_field_reference, 65535, 0 }, /* SoundLoopingTrack */
	{ 64, _tag_field_reference, 65535, 0 }, /* SoundLoopingTrack */
	{ 80, _tag_field_reference, 65535, 0 }, /* SoundLoopingTrack */
	{ 128, _tag_field_reference, 65535, 0 }, /* SoundLoopingTrack */
	{ 144, _tag_field_reference, 65535, 0 }, /* SoundLoopingTrack */
	{ 0, _tag_field_reference, 65535, 0 }, /* SoundLoopingDetail */
	{ 40, _tag_field_reference, 65535, 0 }, /* DeviceMachine */
	{ 56, _tag_field_reference, 65535, 0 }, /* DeviceMachine */
	{ 112, _tag_field_reference, 65535, 0 }, /* DeviceMachine */
	{ 128, _tag_field_reference, 65535, 0 }, /* DeviceMachine */
	{ 144, _tag_field_reference, 65535, 0 }, /* DeviceMachine */
	{ 160, _tag_field_reference, 65535, 0 }, /* DeviceMachine */
	{ 320, _tag_field_block, 20, 72 }, /* DeviceMachine */
	{ 332, _tag_field_block, 21, 32 }, /* DeviceMachine */
	{ 344, _tag_field_block, 65535, 360 }, /* DeviceMachine */
	{ 356, _tag_field_block, 22, 44 }, /* DeviceMachine */
	{ 368, _tag_field_block, 65535, 8 }, /* DeviceMachine */
	{ 416, _tag_field_reference, 65535, 0 }, /* DeviceMachine */
	{ 432, _tag_field_reference, 65535, 0 }, /* DeviceMachine */
	{ 448, _tag_field_reference, 65535, 0 }, /* DeviceMachine */
	{ 464, _tag_field_reference, 65535, 0 }, /* DeviceMachine */
	{ 480, _tag_field_reference, 65535, 0 }, /* DeviceMachine */
	{ 496, _tag_field_reference, 65535, 0 }, /* DeviceMachine */
	{ 524, _tag_field_reference, 65535, 0 }, /* DeviceMachine */
	{ 248, _tag_field_block, 79, 16 }, /* Globals */
	{ 260, _tag_field_block, 80, 16 }, /* Globals */
	{ 272, _tag_field_block, 81, 128 }, /* Globals */
	{ 284, _tag_field_block, 65535, 644 }, /* Globals */
	{ 296, _tag_field_block, 82, 68 }, /* Globals */
	{ 308, _tag_field_block, 83, 428 }, /* Globals */
	{ 320, _tag_field_block, 84, 304 }, /* Globals */
	{ 332, _tag_field_block, 85, 16 }, /* Globals */
	{ 344, _tag_field_block, 86, 16 }, /* Globals */
	{ 356, _tag_field_block, 87, 160 }, /* Globals */
	{ 368, _tag_field_block, 89, 244 }, /* Globals */
	{ 380, _tag_field_block, 90, 192 }, /* Globals */
	{ 392, _tag_field_block, 91, 152 }, /* Globals */
	{ 404, _tag_field_block, 92, 884 }, /* Globals */
	{ 416, _tag_field_block, 65535, 148 }, /* Globals */
	{ 0, _tag_field_reference, 65535, 0 }, /* GlobalsSound */
	{ 0, _tag_field_reference, 65535, 0 }, /* GlobalsCamera */
	{ 116, _tag_field_block, 65535, 4 }, /* GlobalsPlayerControl */
	{ 4, _tag_field_reference, 65535, 0 }, /* GlobalsGrenade */
	{ 20, _tag_field_reference, 65535, 0 }, /* GlobalsGrenade */
	{ 36, _tag_field_reference, 65535, 0 }, /* GlobalsGrenade */
	{ 52, _tag_field_reference, 65535, 0 }, /* GlobalsGrenade */
	{ 0, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 16, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 32, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 48, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 64, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 80, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 96, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 172, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 188, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 204, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 220, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 236, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 252, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 268, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 284, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 300, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 412, _tag_field_reference, 65535, 0 }, /* GlobalsRasterizerData */
	{ 0, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 16, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 32, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 48, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 64, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 80, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 96, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 112, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 128, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 144, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 160, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 176, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 192, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 208, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 224, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 240, _tag_field_reference, 65535, 0 }, /* GlobalsInterfaceBitmaps */
	{ 0, _tag_field_reference, 65535, 0 }, /* GlobalsWeapon */
	{ 0, _tag_field_reference, 65535, 0 }, /* GlobalsCheatPowerup */
	{ 0, _tag_field_reference, 65535, 0 }, /* GlobalsMultiplayerInformation */
	{ 16, _tag_field_reference, 65535, 0 }, /* GlobalsMultiplayerInformation */
	{ 32, _tag_field_block, 88, 16 }, /* GlobalsMultiplayerInformation */
	{ 44, _tag_field_reference, 65535, 0 }, /* GlobalsMultiplayerInformation */
	{ 60, _tag_field_reference, 65535, 0 }, /* GlobalsMultiplayerInformation */
	{ 76, _tag_field_reference, 65535, 0 }, /* GlobalsMultiplayerInformation */
	{ 92, _tag_field_block, 79, 16 }, /* GlobalsMultiplayerInformation */
	{ 0, _tag_field_reference, 65535, 0 }, /* GlobalsVehicle */
	{ 0, _tag_field_reference, 65535, 0 }, /* GlobalsPlayerInformation */
	{ 184, _tag_field_reference, 65535, 0 }, /* GlobalsPlayerInformation */
	{ 0, _tag_field_reference, 65535, 0 }, /* GlobalsFirstPersonInterface */
	{ 16, _tag_field_reference, 65535, 0 }, /* GlobalsFirstPersonInterface */
	{ 32, _tag_field_reference, 65535, 0 }, /* GlobalsFirstPersonInterface */
	{ 52, _tag_field_reference, 65535, 0 }, /* GlobalsFirstPersonInterface */
	{ 72, _tag_field_reference, 65535, 0 }, /* GlobalsFirstPersonInterface */
	{ 88, _tag_field_reference, 65535, 0 }, /* GlobalsFirstPersonInterface */
	{ 16, _tag_field_reference, 65535, 0 }, /* GlobalsFallingDamage */
	{ 44, _tag_field_reference, 65535, 0 }, /* GlobalsFallingDamage */
	{ 60, _tag_field_reference, 65535, 0 }, /* GlobalsFallingDamage */
	{ 76, _tag_field_reference, 65535, 0 }, /* GlobalsFallingDamage */
	{ 92, _tag_field_reference, 65535, 0 }, /* GlobalsFallingDamage */
	{ 108, _tag_field_reference, 65535, 0 }, /* GlobalsFallingDamage */
	{ 740, _tag_field_reference, 65535, 0 }, /* GlobalsMaterial */
	{ 756, _tag_field_reference, 65535, 0 }, /* GlobalsMaterial */
	{ 796, _tag_field_block, 93, 128 }, /* GlobalsMaterial */
	{ 868, _tag_field_reference, 65535, 0 }, /* GlobalsMaterial */
	{ 0, _tag_field_reference, 65535, 0 }, /* GlobalsBreakableSurfaceParticleEffect */
	{ 4, _tag_field_reference, 65535, 0 }, /* Meter */
	{ 20, _tag_field_reference, 65535, 0 }, /* Meter */
	{ 152, _tag_field_data, 65535, 0 }, /* Meter */
	{ 92, _tag_field_reference, 65535, 0 }, /* LightVolume */
	{ 288, _tag_field_block, 65535, 176 }, /* LightVolume */
	{ 172, _tag_field_block, 97, 64 }, /* GBXModel */
	{ 184, _tag_field_block, 65535, 156 }, /* GBXModel */
	{ 196, _tag_field_block, 98, 76 }, /* GBXModel */
	{ 208, _tag_field_block, 100, 48 }, /* GBXModel */
	{ 220, _tag_field_block, 102, 32 }, /* GBXModel */
	{ 52, _tag_field_block, 65535, 32 }, /* ModelMarker */
	{ 64, _tag_field_block, 99, 88 }, /* ModelRegion */
	{ 76, _tag_field_block, 65535, 80 }, /* ModelRegionPermutation */
	{ 36, _tag_field_block, 101, 132 }, /* GBXModelGeometry */
	{ 32, _tag_field_block, 65535, 68 }, /* GBXModelGeometryPart */
	{ 44, _tag_field_block, 65535, 32 }, /* GBXModelGeometryPart */
	{ 56, _tag_field_block, 65535, 6 }, /* GBXModelGeometryPart */
	{ 76, _tag_field_pointer, 65535, 0 }, /* GBXModelGeometryPart */
	{ 80, _tag_field_pointer, 65535, 0 }, /* GBXModelGeometryPart */
	{ 96, _tag_field_pointer, 65535, 0 }, /* GBXModelGeometryPart */
	{ 100, _tag_field_pointer, 65535, 0 }, /* GBXModelGeometryPart */
	{ 0, _tag_field_reference, 65535, 0 }, /* ModelShaderReference */
	{ 172, _tag_field_block, 97, 64 }, /* Model */
	{ 184, _tag_field_block, 65535, 156 }, /* Model */
	{ 196, _tag_field_block, 98, 76 }, /* Model */
	{ 208, _tag_field_block, 104, 48 }, /* Model */
	{ 220, _tag_field_block, 102, 32 }, /* Model */
	{ 36, _tag_field_block, 105, 104 }, /* ModelGeometry */
	{ 32, _tag_field_block, 65535, 68 }, /* ModelGeometryPart */
	{ 44, _tag_field_block, 65535, 32 }, /* ModelGeometryPart */
	{ 56, _tag_field_block, 65535, 6 }, /* ModelGeometryPart */
	{ 76, _tag_field_pointer, 65535, 0 }, /* ModelGeometryPart */
	{ 80, _tag_field_pointer, 65535, 0 }, /* ModelGeometryPart */
	{ 96, _tag_field_pointer, 65535, 0 }, /* ModelGeometryPart */
	{ 100, _tag_field_pointer, 65535, 0 }, /* ModelGeometryPart */
	{ 0, _tag_field_block, 107, 68 }, /* MultiplayerScenarioDescription */
	{ 0, _tag_field_reference, 65535, 0 }, /* MultiplayerScenarioDescriptionScenarioDescription */
	{ 16, _tag_field_reference, 65535, 0 }, /* MultiplayerScenarioDescriptionScenarioDescription */
	{ 56, _tag_field_reference, 65535, 0 }, /* PreferencesNetworkGame */
	{ 76, _tag_field_reference, 65535, 0 }, /* PreferencesNetworkGame */
	{ 40, _tag_field_reference, 65535, 0 }, /* Object */
	{ 56, _tag_field_reference, 65535, 0 }, /* Object */
	{ 112, _tag_field_reference, 65535, 0 }, /* Object */
	{ 128, _tag_field_reference, 65535, 0 }, /* Object */
	{ 144, _tag_field_reference, 65535, 0 }, /* Object */
	{ 160, _tag_field_reference, 65535, 0 }, /* Object */
	{ 320, _tag_field_block, 20, 72 }, /* Object */
	{ 332, _tag_field_block, 21, 32 }, /* Object */
	{ 344, _tag_field_block, 65535, 360 }, /* Object */
	{ 356, _tag_field_block, 22, 44 }, /* Object */
	{ 368, _tag_field_block, 65535, 8 }, /* Object */
	{ 4, _tag_field_reference, 65535, 0 }, /* Particle */
	{ 20, _tag_field_reference, 65535, 0 }, /* Particle */
	{ 36, _tag_field_reference, 65535, 0 }, /* Particle */
	{ 72, _tag_field_reference, 65535, 0 }, /* Particle */
	{ 88, _tag_field_reference, 65535, 0 }, /* Particle */
	{ 252, _tag_field_reference, 65535, 0 }, /* Particle */
	{ 56, _tag_field_reference, 65535, 0 }, /* ParticleSystem */
	{ 80, _tag_field_block, 65535, 4 }, /* ParticleSystem */
	{ 92, _tag_field_block, 112, 128 }, /* ParticleSystem */
	{ 92, _tag_field_block, 65535, 4 }, /* ParticleSystemType */
	{ 104, _tag_field_block, 113, 192 }, /* ParticleSystemType */
	{ 116, _tag_field_block, 114, 376 }, /* ParticleSystemType */
	{ 180, _tag_field_block, 65535, 4 }, /* ParticleSystemTypeStates */
	{ 48, _tag_field_reference, 65535, 0 }, /* ParticleSystemTypeParticleState */
	{ 132, _tag_field_reference, 65535, 0 }, /* ParticleSystemTypeParticleState */
	{ 260, _tag_field_reference, 65535, 0 }, /* ParticleSystemTypeParticleState */
	{ 364, _tag_field_block, 65535, 4 }, /* ParticleSystemTypeParticleState */
	{ 92, _tag_field_block, 65535, 36 }, /* Physics */
	{ 104, _tag_field_block, 65535, 128 }, /* Physics */
	{ 116, _tag_field_block, 65535, 128 }, /* Physics */
	{ 40, _tag_field_reference, 65535, 0 }, /* Placeholder */
	{ 56, _tag_field_reference, 65535, 0 }, /* Placeholder */
	{ 112, _tag_field_reference, 65535, 0 }, /* Placeholder */
	{ 128, _tag_field_reference, 65535, 0 }, /* Placeholder */
	{ 144, _tag_field_reference, 65535, 0 }, /* Placeholder */
	{ 160, _tag_field_reference, 65535, 0 }, /* Placeholder */
	{ 320, _tag_field_block, 20, 72 }, /* Placeholder */
	{ 332, _tag_field_block, 21, 32 }, /* Placeholder */
	{ 344, _tag_field_block, 65535, 360 }, /* Placeholder */
	{ 356, _tag_field_block, 22, 44 }, /* Placeholder */
	{ 368, _tag_field_block, 65535, 8 }, /* Placeholder */
	{ 40, _tag_field_reference, 65535, 0 }, /* Projectile */
	{ 56, _tag_field_reference, 65535, 0 }, /* Projectile */
	{ 112, _tag_field_reference, 65535, 0 }, /* Projectile */
	{ 128, _tag_field_reference, 65535, 0 }, /* Projectile */
	{ 144, _tag_field_reference, 65535, 0 }, /* Projectile */
	{ 160, _tag_field_reference, 65535, 0 }, /* Projectile */
	{ 320, _tag_field_block, 20, 72 }, /* Projectile */
	{ 332, _tag_field_block, 21, 32 }, /* Projectile */
	{ 344, _tag_field_block, 65535, 360 }, /* Projectile */
	{ 356, _tag_field_block, 22, 44 }, /* Projectile */
	{ 368, _tag_field_block, 65535, 8 }, /* Projectile */
	{ 396, _tag_field_reference, 65535, 0 }, /* Projectile */
	{ 428, _tag_field_reference, 65535, 0 }, /* Projectile */
	{ 500, _tag_field_reference, 65535, 0 }, /* Projectile */
	{ 516, _tag_field_reference, 65535, 0 }, /* Projectile */
	{ 532, _tag_field_reference, 65535, 0 }, /* Projectile */
	{ 548, _tag_field_reference, 65535, 0 }, /* Projectile */
	{ 576, _tag_field_block, 118, 160 }, /* Projectile */
	{ 4, _tag_field_reference, 65535, 0 }, /* ProjectileMaterialResponse */
	{ 60, _tag_field_reference, 65535, 0 }, /* ProjectileMaterialResponse */
	{ 104, _tag_field_reference, 65535, 0 }, /* ProjectileMaterialResponse */
	{ 36, _tag_field_block, 120, 604 }, /* WeatherParticleSystem */
	{ 172, _tag_field_reference, 65535, 0 }, /* WeatherParticleSystemParticleType */
	{ 404, _tag_field_reference, 65535, 0 }, /* WeatherParticleSystemParticleType */
	{ 500, _tag_field_reference, 65535, 0 }, /* WeatherParticleSystemParticleType */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioStructureBSP */
	{ 164, _tag_field_block, 122, 20 }, /* ScenarioStructureBSP */
	{ 176, _tag_field_block, 34, 96 }, /* ScenarioStructureBSP */
	{ 188, _tag_field_block, 65535, 6 }, /* ScenarioStructureBSP */
	{ 224, _tag_field_block, 65535, 16 }, /* ScenarioStructureBSP */
	{ 236, _tag_field_block, 65535, 8 }, /* ScenarioStructureBSP */
	{ 248, _tag_field_block, 65535, 6 }, /* ScenarioStructureBSP */
	{ 260, _tag_field_block, 123, 32 }, /* ScenarioStructureBSP */
	{ 284, _tag_field_block, 125, 16 }, /* ScenarioStructureBSP */
	{ 296, _tag_field_block, 65535, 16 }, /* ScenarioStructureBSP */
	{ 308, _tag_field_block, 126, 104 }, /* ScenarioStructureBSP */
	{ 320, _tag_field_data, 65535, 0 }, /* ScenarioStructureBSP */
	{ 340, _tag_field_block, 129, 64 }, /* ScenarioStructureBSP */
	{ 364, _tag_field_block, 65535, 48 }, /* ScenarioStructureBSP */
	{ 376, _tag_field_block, 130, 32 }, /* ScenarioStructureBSP */
	{ 388, _tag_field_block, 65535, 40 }, /* ScenarioStructureBSP */
	{ 400, _tag_field_block, 131, 136 }, /* ScenarioStructureBSP */
	{ 436, _tag_field_block, 132, 240 }, /* ScenarioStructureBSP */
	{ 448, _tag_field_block, 133, 32 }, /* ScenarioStructureBSP */
	{ 484, _tag_field_block, 65535, 1 }, /* ScenarioStructureBSP */
	{ 496, _tag_field_block, 65535, 1 }, /* ScenarioStructureBSP */
	{ 508, _tag_field_block, 134, 116 }, /* ScenarioStructureBSP */
	{ 520, _tag_field_block, 135, 80 }, /* ScenarioStructureBSP */
	{ 532, _tag_field_data, 65535, 0 }, /* ScenarioStructureBSP */
	{ 576, _tag_field_block, 65535, 60 }, /* ScenarioStructureBSP */
	{ 588, _tag_field_block, 136, 64 }, /* ScenarioStructureBSP */
	{ 600, _tag_field_block, 65535, 16 }, /* ScenarioStructureBSP */
	{ 624, _tag_field_block, 137, 24 }, /* ScenarioStructureBSP */
	{ 636, _tag_field_block, 139, 24 }, /* ScenarioStructureBSP */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioStructureBSPCollisionMaterial */
	{ 20, _tag_field_block, 124, 256 }, /* ScenarioStructureBSPLightmap */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioStructureBSPMaterial */
	{ 192, _tag_field_pointer, 65535, 0 }, /* ScenarioStructureBSPMaterial */
	{ 212, _tag_field_pointer, 65535, 0 }, /* ScenarioStructureBSPMaterial */
	{ 216, _tag_field_data, 65535, 0 }, /* ScenarioStructureBSPMaterial */
	{ 236, _tag_field_data, 65535, 0 }, /* ScenarioStructureBSPMaterial */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioStructureBSPLensFlare */
	{ 40, _tag_field_block, 65535, 8 }, /* ScenarioStructureBSPCluster */
	{ 52, _tag_field_block, 127, 36 }, /* ScenarioStructureBSPCluster */
	{ 68, _tag_field_block, 65535, 4 }, /* ScenarioStructureBSPCluster */
	{ 80, _tag_field_block, 128, 64 }, /* ScenarioStructureBSPCluster */
	{ 92, _tag_field_block, 65535, 2 }, /* ScenarioStructureBSPCluster */
	{ 24, _tag_field_block, 65535, 4 }, /* ScenarioStructureBSPSubcluster */
	{ 36, _tag_field_reference, 65535, 0 }, /* ScenarioStructureBSPMirror */
	{ 52, _tag_field_block, 65535, 12 }, /* ScenarioStructureBSPMirror */
	{ 52, _tag_field_block, 65535, 12 }, /* ScenarioStructureBSPClusterPortal */
	{ 20, _tag_field_block, 65535, 12 }, /* ScenarioStructureBSPFogPlane */
	{ 32, _tag_field_reference, 65535, 0 }, /* ScenarioStructureBSPFogPalette */
	{ 32, _tag_field_reference, 65535, 0 }, /* ScenarioStructureBSPWeatherPalette */
	{ 128, _tag_field_reference, 65535, 0 }, /* ScenarioStructureBSPWeatherPalette */
	{ 20, _tag_field_block, 65535, 16 }, /* ScenarioStructureBSPWeatherPolyhedron */
	{ 32, _tag_field_reference, 65535, 0 }, /* ScenarioStructureBSPBackgroundSoundPalette */
	{ 32, _tag_field_reference, 65535, 0 }, /* ScenarioStructureBSPSoundEnvironmentPalette */
	{ 0, _tag_field_block, 65535, 32 }, /* ScenarioStructureBSPDetailObjectData */
	{ 12, _tag_field_block, 65535, 6 }, /* ScenarioStructureBSPDetailObjectData */
	{ 24, _tag_field_block, 65535, 2 }, /* ScenarioStructureBSPDetailObjectData */
	{ 36, _tag_field_block, 65535, 16 }, /* ScenarioStructureBSPDetailObjectData */
	{ 0, _tag_field_block, 138, 16 }, /* ScenarioStructureBSPGlobalMapLeaf */
	{ 12, _tag_field_block, 65535, 4 }, /* ScenarioStructureBSPGlobalMapLeaf */
	{ 4, _tag_field_block, 65535, 8 }, /* ScenarioStructureBSPMapLeafFace */
	{ 12, _tag_field_block, 65535, 12 }, /* ScenarioStructureBSPGlobalLeafPortal */
	{ 40, _tag_field_reference, 65535, 0 }, /* Scenery */
	{ 56, _tag_field_reference, 65535, 0 }, /* Scenery */
	{ 112, _tag_field_reference, 65535, 0 }, /* Scenery */
	{ 128, _tag_field_reference, 65535, 0 }, /* Scenery */
	{ 144, _tag_field_reference, 65535, 0 }, /* Scenery */
	{ 160, _tag_field_reference, 65535, 0 }, /* Scenery */
	{ 320, _tag_field_block, 20, 72 }, /* Scenery */
	{ 332, _tag_field_block, 21, 32 }, /* Scenery */
	{ 344, _tag_field_block, 65535, 360 }, /* Scenery */
	{ 356, _tag_field_block, 22, 44 }, /* Scenery */
	{ 368, _tag_field_block, 65535, 8 }, /* Scenery */
	{ 56, _tag_field_reference, 65535, 0 }, /* ShaderTransparentChicagoExtended */
	{ 72, _tag_field_block, 142, 16 }, /* ShaderTransparentChicagoExtended */
	{ 84, _tag_field_block, 143, 220 }, /* ShaderTransparentChicagoExtended */
	{ 96, _tag_field_block, 143, 220 }, /* ShaderTransparentChicagoExtended */
	{ 0, _tag_field_reference, 65535, 0 }, /* ShaderTransparentExtraLayer */
	{ 108, _tag_field_reference, 65535, 0 }, /* ShaderTransparentChicagoMap */
	{ 56, _tag_field_reference, 65535, 0 }, /* ShaderTransparentChicago */
	{ 72, _tag_field_block, 142, 16 }, /* ShaderTransparentChicago */
	{ 84, _tag_field_block, 143, 220 }, /* ShaderTransparentChicago */
	{ 0, _tag_field_reference, 65535, 0 }, /* Scenario */
	{ 16, _tag_field_reference, 65535, 0 }, /* Scenario */
	{ 32, _tag_field_reference, 65535, 0 }, /* Scenario */
	{ 48, _tag_field_block, 146, 16 }, /* Scenario */
	{ 64, _tag_field_block, 147, 32 }, /* Scenario */
	{ 236, _tag_field_block, 65535, 8 }, /* Scenario */
	{ 248, _tag_field_block, 65535, 120 }, /* Scenario */
	{ 260, _tag_field_data, 65535, 0 }, /* Scenario */
	{ 280, _tag_field_block, 148, 48 }, /* Scenario */
	{ 292, _tag_field_block, 65535, 36 }, /* Scenario */
	{ 516, _tag_field_block, 65535, 36 }, /* Scenario */
	{ 528, _tag_field_block, 65535, 72 }, /* Scenario */
	{ 540, _tag_field_block, 149, 48 }, /* Scenario */
	{ 552, _tag_field_block, 65535, 120 }, /* Scenario */
	{ 564, _tag_field_block, 150, 48 }, /* Scenario */
	{ 576, _tag_field_block, 65535, 120 }, /* Scenario */
	{ 588, _tag_field_block, 151, 48 }, /* Scenario */
	{ 600, _tag_field_block, 65535, 40 }, /* Scenario */
	{ 612, _tag_field_block, 152, 48 }, /* Scenario */
	{ 624, _tag_field_block, 65535, 92 }, /* Scenario */
	{ 636, _tag_field_block, 153, 48 }, /* Scenario */
	{ 648, _tag_field_block, 65535, 52 }, /* Scenario */
	{ 660, _tag_field_block, 65535, 64 }, /* Scenario */
	{ 672, _tag_field_block, 154, 48 }, /* Scenario */
	{ 684, _tag_field_block, 65535, 64 }, /* Scenario */
	{ 696, _tag_field_block, 155, 48 }, /* Scenario */
	{ 708, _tag_field_block, 65535, 88 }, /* Scenario */
	{ 720, _tag_field_block, 156, 48 }, /* Scenario */
	{ 732, _tag_field_block, 65535, 40 }, /* Scenario */
	{ 744, _tag_field_block, 157, 48 }, /* Scenario */
	{ 840, _tag_field_block, 158, 104 }, /* Scenario */
	{ 852, _tag_field_block, 65535, 52 }, /* Scenario */
	{ 864, _tag_field_block, 65535, 96 }, /* Scenario */
	{ 876, _tag_field_block, 159, 64 }, /* Scenario */
	{ 888, _tag_field_block, 160, 148 }, /* Scenario */
	{ 900, _tag_field_block, 161, 144 }, /* Scenario */
	{ 912, _tag_field_block, 162, 204 }, /* Scenario */
	{ 924, _tag_field_block, 65535, 8 }, /* Scenario */
	{ 936, _tag_field_block, 65535, 16 }, /* Scenario */
	{ 948, _tag_field_block, 163, 16 }, /* Scenario */
	{ 960, _tag_field_block, 164, 48 }, /* Scenario */
	{ 1056, _tag_field_block, 165, 16 }, /* Scenario */
	{ 1068, _tag_field_block, 166, 176 }, /* Scenario */
	{ 1080, _tag_field_block, 168, 96 }, /* Scenario */
	{ 1092, _tag_field_block, 169, 60 }, /* Scenario */
	{ 1104, _tag_field_block, 65535, 40 }, /* Scenario */
	{ 1116, _tag_field_block, 65535, 40 }, /* Scenario */
	{ 1128, _tag_field_block, 170, 116 }, /* Scenario */
	{ 1140, _tag_field_data, 65535, 0 }, /* Scenario */
	{ 1160, _tag_field_data, 65535, 0 }, /* Scenario */
	{ 1180, _tag_field_block, 172, 92 }, /* Scenario */
	{ 1192, _tag_field_block, 65535, 92 }, /* Scenario */
	{ 1204, _tag_field_block, 173, 40 }, /* Scenario */
	{ 1216, _tag_field_block, 174, 52 }, /* Scenario */
	{ 1252, _tag_field_block, 65535, 92 }, /* Scenario */
	{ 1264, _tag_field_block, 65535, 104 }, /* Scenario */
	{ 1276, _tag_field_block, 65535, 96 }, /* Scenario */
	{ 1396, _tag_field_reference, 65535, 0 }, /* Scenario */
	{ 1412, _tag_field_reference, 65535, 0 }, /* Scenario */
	{ 1428, _tag_field_reference, 65535, 0 }, /* Scenario */
	{ 1444, _tag_field_block, 175, 32 }, /* Scenario */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioSky */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioChildScenario */
	{ 28, _tag_field_data, 65535, 0 }, /* ScenarioEditorComment */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioSceneryPalette */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioBipedPalette */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioVehiclePalette */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioEquipmentPalette */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioWeaponPalette */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioMachinePalette */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioControlPalette */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioLightFixturePalette */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioSoundSceneryPalette */
	{ 40, _tag_field_reference, 65535, 0 }, /* ScenarioPlayerStartingProfile */
	{ 60, _tag_field_reference, 65535, 0 }, /* ScenarioPlayerStartingProfile */
	{ 44, _tag_field_data, 65535, 0 }, /* ScenarioRecordedAnimation */
	{ 20, _tag_field_reference, 65535, 0 }, /* ScenarioNetgameFlags */
	{ 80, _tag_field_reference, 65535, 0 }, /* ScenarioNetgameEquipment */
	{ 60, _tag_field_reference, 65535, 0 }, /* ScenarioStartingEquipment */
	{ 76, _tag_field_reference, 65535, 0 }, /* ScenarioStartingEquipment */
	{ 92, _tag_field_reference, 65535, 0 }, /* ScenarioStartingEquipment */
	{ 108, _tag_field_reference, 65535, 0 }, /* ScenarioStartingEquipment */
	{ 124, _tag_field_reference, 65535, 0 }, /* ScenarioStartingEquipment */
	{ 140, _tag_field_reference, 65535, 0 }, /* ScenarioStartingEquipment */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioDecalPalette */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioDetailObjectCollectionPalette */
	{ 0, _tag_field_reference, 65535, 0 }, /* ScenarioActorPalette */
	{ 128, _tag_field_block, 167, 232 }, /* ScenarioEncounter */
	{ 140, _tag_field_block, 65535, 172 }, /* ScenarioEncounter */
	{ 152, _tag_field_block, 65535, 24 }, /* ScenarioEncounter */
	{ 164, _tag_field_block, 65535, 52 }, /* ScenarioEncounter */
	{ 196, _tag_field_block, 65535, 80 }, /* ScenarioSquad */
	{ 208, _tag_field_block, 65535, 28 }, /* ScenarioSquad */
	{ 48, _tag_field_block, 65535, 32 }, /* ScenarioCommandList */
	{ 60, _tag_field_block, 65535, 20 }, /* ScenarioCommandList */
	{ 32, _tag_field_reference, 65535, 0 }, /* ScenarioAIAnimationReference */
	{ 80, _tag_field_block, 65535, 84 }, /* ScenarioAIConversation */
	{ 92, _tag_field_block, 171, 124 }, /* ScenarioAIConversation */
	{ 28, _tag_field_reference, 65535, 0 }, /* ScenarioAIConversationLine */
	{ 44, _tag_field_reference, 65535, 0 }, /* ScenarioAIConversationLine */
	{ 60, _tag_field_reference, 65535, 0 }, /* ScenarioAIConversationLine */
	{ 76, _tag_field_reference, 65535, 0 }, /* ScenarioAIConversationLine */
	{ 92, _tag_field_reference, 65535, 0 }, /* ScenarioAIConversationLine */
	{ 108, _tag_field_reference, 65535, 0 }, /* ScenarioAIConversationLine */
	{ 80, _tag_field_block, 65535, 36 }, /* ScenarioScript */
	{ 24, _tag_field_reference, 65535, 0 }, /* ScenarioReference */
	{ 32, _tag_field_data, 65535, 0 }, /* ScenarioSourceFile */
	{ 8, _tag_field_pointer, 65535, 0 }, /* ScenarioBSP */
	{ 16, _tag_field_reference, 65535, 0 }, /* ScenarioBSP */
	{ 48, _tag_field_reference, 65535, 0 }, /* ShaderEnvironment */
	{ 136, _tag_field_reference, 65535, 0 }, /* ShaderEnvironment */
	{ 184, _tag_field_reference, 65535, 0 }, /* ShaderEnvironment */
	{ 204, _tag_field_reference, 65535, 0 }, /* ShaderEnvironment */
	{ 252, _tag_field_reference, 65535, 0 }, /* ShaderEnvironment */
	{ 296, _tag_field_reference, 65535, 0 }, /* ShaderEnvironment */
	{ 596, _tag_field_reference, 65535, 0 }, /* ShaderEnvironment */
	{ 804, _tag_field_reference, 65535, 0 }, /* ShaderEnvironment */
	{ 100, _tag_field_reference, 65535, 0 }, /* ShaderTransparentGlass */
	{ 172, _tag_field_reference, 65535, 0 }, /* ShaderTransparentGlass */
	{ 192, _tag_field_reference, 65535, 0 }, /* ShaderTransparentGlass */
	{ 344, _tag_field_reference, 65535, 0 }, /* ShaderTransparentGlass */
	{ 364, _tag_field_reference, 65535, 0 }, /* ShaderTransparentGlass */
	{ 416, _tag_field_reference, 65535, 0 }, /* ShaderTransparentGlass */
	{ 436, _tag_field_reference, 65535, 0 }, /* ShaderTransparentGlass */
	{ 0, _tag_field_reference, 65535, 0 }, /* Sky */
	{ 16, _tag_field_reference, 65535, 0 }, /* Sky */
	{ 152, _tag_field_reference, 65535, 0 }, /* Sky */
	{ 172, _tag_field_block, 65535, 36 }, /* Sky */
	{ 184, _tag_field_block, 65535, 36 }, /* Sky */
	{ 196, _tag_field_block, 179, 116 }, /* Sky */
	{ 0, _tag_field_reference, 65535, 0 }, /* SkyLight */
	{ 76, _tag_field_reference, 65535, 0 }, /* ShaderTransparentMeter */
	{ 112, _tag_field_reference, 65535, 0 }, /* Sound */
	{ 152, _tag_field_block, 182, 72 }, /* Sound */
	{ 60, _tag_field_block, 183, 124 }, /* SoundPitchRange */
	{ 64, _tag_field_data, 65535, 0 }, /* SoundPermutation */
	{ 84, _tag_field_data, 65535, 0 }, /* SoundPermutation */
	{ 104, _tag_field_data, 65535, 0 }, /* SoundPermutation */
	{ 164, _tag_field_reference, 65535, 0 }, /* ShaderModel */
	{ 188, _tag_field_reference, 65535, 0 }, /* ShaderModel */
	{ 220, _tag_field_reference, 65535, 0 }, /* ShaderModel */
	{ 356, _tag_field_reference, 65535, 0 }, /* ShaderModel */
	{ 56, _tag_field_reference, 65535, 0 }, /* ShaderTransparentGeneric */
	{ 72, _tag_field_block, 142, 16 }, /* ShaderTransparentGeneric */
	{ 84, _tag_field_block, 186, 100 }, /* ShaderTransparentGeneric */
	{ 96, _tag_field_block, 65535, 112 }, /* ShaderTransparentGeneric */
	{ 28, _tag_field_reference, 65535, 0 }, /* ShaderTransparentGenericMap */
	{ 212, _tag_field_reference, 65535, 0 }, /* ShaderTransparentPlasma */
	{ 284, _tag_field_reference, 65535, 0 }, /* ShaderTransparentPlasma */
	{ 40, _tag_field_reference, 65535, 0 }, /* SoundScenery */
	{ 56, _tag_field_reference, 65535, 0 }, /* SoundScenery */
	{ 112, _tag_field_reference, 65535, 0 }, /* SoundScenery */
	{ 128, _tag_field_reference, 65535, 0 }, /* SoundScenery */
	{ 144, _tag_field_reference, 65535, 0 }, /* SoundScenery */
	{ 160, _tag_field_reference, 65535, 0 }, /* SoundScenery */
	{ 320, _tag_field_block, 20, 72 }, /* SoundScenery */
	{ 332, _tag_field_block, 21, 32 }, /* SoundScenery */
	{ 344, _tag_field_block, 65535, 360 }, /* SoundScenery */
	{ 356, _tag_field_block, 22, 44 }, /* SoundScenery */
	{ 368, _tag_field_block, 65535, 8 }, /* SoundScenery */
	{ 0, _tag_field_block, 190, 20 }, /* StringList */
	{ 0, _tag_field_data, 65535, 0 }, /* StringListString */
	{ 76, _tag_field_reference, 65535, 0 }, /* ShaderTransparentWater */
	{ 156, _tag_field_reference, 65535, 0 }, /* ShaderTransparentWater */
	{ 200, _tag_field_reference, 65535, 0 }, /* ShaderTransparentWater */
	{ 292, _tag_field_block, 65535, 76 }, /* ShaderTransparentWater */
	{ 0, _tag_field_block, 193, 16 }, /* TagCollection */
	{ 0, _tag_field_reference, 65535, 0 }, /* TagCollectionTag */
	{ 4, _tag_field_block, 65535, 60 }, /* CameraTrack */
	{ 16, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 32, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 48, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 112, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 128, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 144, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 160, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 176, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 192, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 208, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 224, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 240, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 256, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 272, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 288, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 304, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 320, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 352, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 368, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 384, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 400, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 480, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 496, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 512, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 528, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 544, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 560, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 576, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 592, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 608, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 624, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 640, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 656, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 672, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 688, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 704, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 720, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 736, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 800, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 816, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 832, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 848, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 864, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 880, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 896, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 912, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 928, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 944, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 960, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 976, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 992, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1008, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1024, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1040, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1056, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1072, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1088, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1104, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1120, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1136, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1152, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1168, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1184, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1200, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1216, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1232, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1296, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1312, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1328, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1344, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1360, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1376, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1392, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1408, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1424, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1440, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1456, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1472, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1488, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1552, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1568, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1584, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1600, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1616, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1632, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1648, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1664, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1680, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1696, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1744, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1760, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1776, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1792, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1808, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1824, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1840, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1856, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1872, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1888, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1904, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1920, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1936, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 1984, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2000, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2016, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2032, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2048, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2064, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2080, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2096, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2112, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2128, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2144, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2160, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2176, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2192, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2208, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2224, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2240, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2256, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2272, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2288, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2304, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2384, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2400, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2416, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2432, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2448, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2464, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2480, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2496, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2512, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2528, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2544, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2560, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2576, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2592, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2608, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2624, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2640, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2656, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2672, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2688, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2704, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2720, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2736, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2848, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2864, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2880, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2896, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2912, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2928, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 2944, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 3024, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 3040, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 3056, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 3072, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 3088, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 3168, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 3184, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 3200, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 3216, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 3232, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 3248, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 3264, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 3280, _tag_field_reference, 65535, 0 }, /* Dialogue */
	{ 72, _tag_field_reference, 65535, 0 }, /* UnitHUDInterface */
	{ 124, _tag_field_block, 60, 480 }, /* UnitHUDInterface */
	{ 176, _tag_field_reference, 65535, 0 }, /* UnitHUDInterface */
	{ 228, _tag_field_block, 60, 480 }, /* UnitHUDInterface */
	{ 280, _tag_field_reference, 65535, 0 }, /* UnitHUDInterface */
	{ 416, _tag_field_reference, 65535, 0 }, /* UnitHUDInterface */
	{ 468, _tag_field_block, 60, 480 }, /* UnitHUDInterface */
	{ 520, _tag_field_reference, 65535, 0 }, /* UnitHUDInterface */
	{ 656, _tag_field_reference, 65535, 0 }, /* UnitHUDInterface */
	{ 708, _tag_field_block, 60, 480 }, /* UnitHUDInterface */
	{ 760, _tag_field_reference, 65535, 0 }, /* UnitHUDInterface */
	{ 812, _tag_field_block, 60, 480 }, /* UnitHUDInterface */
	{ 932, _tag_field_block, 197, 132 }, /* UnitHUDInterface */
	{ 960, _tag_field_block, 198, 56 }, /* UnitHUDInterface */
	{ 972, _tag_field_block, 199, 324 }, /* UnitHUDInterface */
	{ 36, _tag_field_reference, 65535, 0 }, /* UnitHUDInterfaceAuxiliaryOverlay */
	{ 88, _tag_field_block, 60, 480 }, /* UnitHUDInterfaceAuxiliaryOverlay */
	{ 0, _tag_field_reference, 65535, 0 }, /* UnitHUDInterfaceHUDSound */
	{ 56, _tag_field_reference, 65535, 0 }, /* UnitHUDInterfaceAuxiliaryPanel */
	{ 108, _tag_field_block, 60, 480 }, /* UnitHUDInterfaceAuxiliaryPanel */
	{ 160, _tag_field_reference, 65535, 0 }, /* UnitHUDInterfaceAuxiliaryPanel */
	{ 40, _tag_field_reference, 65535, 0 }, /* Unit */
	{ 56, _tag_field_reference, 65535, 0 }, /* Unit */
	{ 112, _tag_field_reference, 65535, 0 }, /* Unit */
	{ 128, _tag_field_reference, 65535, 0 }, /* Unit */
	{ 144, _tag_field_reference, 65535, 0 }, /* Unit */
	{ 160, _tag_field_reference, 65535, 0 }, /* Unit */
	{ 320, _tag_field_block, 20, 72 }, /* Unit */
	{ 332, _tag_field_block, 21, 32 }, /* Unit */
	{ 344, _tag_field_block, 65535, 360 }, /* Unit */
	{ 356, _tag_field_block, 22, 44 }, /* Unit */
	{ 368, _tag_field_block, 65535, 8 }, /* Unit */
	{ 392, _tag_field_reference, 65535, 0 }, /* Unit */
	{ 500, _tag_field_block, 23, 28 }, /* Unit */
	{ 588, _tag_field_reference, 65535, 0 }, /* Unit */
	{ 648, _tag_field_reference, 65535, 0 }, /* Unit */
	{ 680, _tag_field_block, 24, 48 }, /* Unit */
	{ 692, _tag_field_block, 25, 24 }, /* Unit */
	{ 716, _tag_field_block, 65535, 68 }, /* Unit */
	{ 728, _tag_field_block, 26, 36 }, /* Unit */
	{ 740, _tag_field_block, 27, 284 }, /* Unit */
	{ 0, _tag_field_block, 202, 20 }, /* UnicodeStringList */
	{ 0, _tag_field_data, 65535, 0 }, /* UnicodeStringListString */
	{ 0, _tag_field_reference, 65535, 0 }, /* VirtualKeyboard */
	{ 16, _tag_field_reference, 65535, 0 }, /* VirtualKeyboard */
	{ 32, _tag_field_reference, 65535, 0 }, /* VirtualKeyboard */
	{ 48, _tag_field_block, 204, 80 }, /* VirtualKeyboard */
	{ 16, _tag_field_reference, 65535, 0 }, /* VirtualKeyboardVirtualKey */
	{ 32, _tag_field_reference, 65535, 0 }, /* VirtualKeyboardVirtualKey */
	{ 48, _tag_field_reference, 65535, 0 }, /* VirtualKeyboardVirtualKey */
	{ 64, _tag_field_reference, 65535, 0 }, /* VirtualKeyboardVirtualKey */
	{ 40, _tag_field_reference, 65535, 0 }, /* Vehicle */
	{ 56, _tag_field_reference, 65535, 0 }, /* Vehicle */
	{ 112, _tag_field_reference, 65535, 0 }, /* Vehicle */
	{ 128, _tag_field_reference, 65535, 0 }, /* Vehicle */
	{ 144, _tag_field_reference, 65535, 0 }, /* Vehicle */
	{ 160, _tag_field_reference, 65535, 0 }, /* Vehicle */
	{ 320, _tag_field_block, 20, 72 }, /* Vehicle */
	{ 332, _tag_field_block, 21, 32 }, /* Vehicle */
	{ 344, _tag_field_block, 65535, 360 }, /* Vehicle */
	{ 356, _tag_field_block, 22, 44 }, /* Vehicle */
	{ 368, _tag_field_block, 65535, 8 }, /* Vehicle */
	{ 392, _tag_field_reference, 65535, 0 }, /* Vehicle */
	{ 500, _tag_field_block, 23, 28 }, /* Vehicle */
	{ 588, _tag_field_reference, 65535, 0 }, /* Vehicle */
	{ 648, _tag_field_reference, 65535, 0 }, /* Vehicle */
	{ 680, _tag_field_block, 24, 48 }, /* Vehicle */
	{ 692, _tag_field_block, 25, 24 }, /* Vehicle */
	{ 716, _tag_field_block, 65535, 68 }, /* Vehicle */
	{ 728, _tag_field_block, 26, 36 }, /* Vehicle */
	{ 740, _tag_field_block, 27, 284 }, /* Vehicle */
	{ 944, _tag_field_reference, 65535, 0 }, /* Vehicle */
	{ 960, _tag_field_reference, 65535, 0 }, /* Vehicle */
	{ 976, _tag_field_reference, 65535, 0 }, /* Vehicle */
	{ 992, _tag_field_reference, 65535, 0 }, /* Vehicle */
	{ 40, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 56, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 112, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 128, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 144, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 160, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 320, _tag_field_block, 20, 72 }, /* Weapon */
	{ 332, _tag_field_block, 21, 32 }, /* Weapon */
	{ 344, _tag_field_block, 65535, 360 }, /* Weapon */
	{ 356, _tag_field_block, 22, 44 }, /* Weapon */
	{ 368, _tag_field_block, 65535, 8 }, /* Weapon */
	{ 584, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 600, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 744, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 760, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 828, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 884, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 900, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 916, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 932, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 956, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 1056, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 1072, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 1116, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 1132, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 1152, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 1168, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 1184, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 1200, _tag_field_reference, 65535, 0 }, /* Weapon */
	{ 1252, _tag_field_block, 65535, 8 }, /* Weapon */
	{ 1264, _tag_field_block, 207, 112 }, /* Weapon */
	{ 1276, _tag_field_block, 209, 276 }, /* Weapon */
	{ 56, _tag_field_reference, 65535, 0 }, /* WeaponMagazine */
	{ 72, _tag_field_reference, 65535, 0 }, /* WeaponMagazine */
	{ 100, _tag_field_block, 208, 28 }, /* WeaponMagazine */
	{ 12, _tag_field_reference, 65535, 0 }, /* WeaponMagazineObject */
	{ 92, _tag_field_reference, 65535, 0 }, /* WeaponTrigger */
	{ 148, _tag_field_reference, 65535, 0 }, /* WeaponTrigger */
	{ 264, _tag_field_block, 210, 132 }, /* WeaponTrigger */
	{ 36, _tag_field_reference, 65535, 0 }, /* WeaponTriggerFiringEffect */
	{ 52, _tag_field_reference, 65535, 0 }, /* WeaponTriggerFiringEffect */
	{ 68, _tag_field_reference, 65535, 0 }, /* WeaponTriggerFiringEffect */
	{ 84, _tag_field_reference, 65535, 0 }, /* WeaponTriggerFiringEffect */
	{ 100, _tag_field_reference, 65535, 0 }, /* WeaponTriggerFiringEffect */
	{ 116, _tag_field_reference, 65535, 0 }, /* WeaponTriggerFiringEffect */
	{ 0, _tag_field_reference, 65535, 0 }, /* WeaponHUDInterface */
	{ 96, _tag_field_block, 212, 180 }, /* WeaponHUDInterface */
	{ 108, _tag_field_block, 213, 180 }, /* WeaponHUDInterface */
	{ 120, _tag_field_block, 65535, 160 }, /* WeaponHUDInterface */
	{ 132, _tag_field_block, 214, 104 }, /* WeaponHUDInterface */
	{ 144, _tag_field_block, 215, 104 }, /* WeaponHUDInterface */
	{ 172, _tag_field_block, 216, 184 }, /* WeaponHUDInterface */
	{ 72, _tag_field_reference, 65535, 0 }, /* WeaponHUDInterfaceStaticElement */
	{ 124, _tag_field_block, 60, 480 }, /* WeaponHUDInterfaceStaticElement */
	{ 72, _tag_field_reference, 65535, 0 }, /* WeaponHUDInterfaceMeter */
	{ 36, _tag_field_reference, 65535, 0 }, /* WeaponHUDInterfaceCrosshair */
	{ 52, _tag_field_block, 65535, 108 }, /* WeaponHUDInterfaceCrosshair */
	{ 36, _tag_field_reference, 65535, 0 }, /* WeaponHUDInterfaceOverlayElement */
	{ 52, _tag_field_block, 65535, 136 }, /* WeaponHUDInterfaceOverlayElement */
	{ 24, _tag_field_reference, 65535, 0 }, /* WeaponHUDInterfaceScreenEffect */
	{ 40, _tag_field_reference, 65535, 0 }, /* WeaponHUDInterfaceScreenEffect */
};

static const struct tag_layout_struct tag_layout_structs[] = {
	{ 0, 11 }, /* 0 UIWidgetDefinition */
	{ 11, 2 }, /* 1 EventHandlerReference */
	{ 13, 1 }, /* 2 ConditionalWidgetReference */
	{ 14, 1 }, /* 3 ChildWidgetReference */
	{ 15, 1 }, /* 4 UIWidgetCollection */
	{ 16, 1 }, /* 5 UIWidgetCollectionReference */
	{ 17, 3 }, /* 6 Actor */
	{ 20, 6 }, /* 7 ActorVariant */
	{ 26, 3 }, /* 8 Antenna */
	{ 29, 10 }, /* 9 ModelAnimations */
	{ 39, 3 }, /* 10 ModelAnimationsAnimationGraphUnitSeat */
	{ 42, 3 }, /* 11 ModelAnimationsAnimationGraphWeapon */
	{ 45, 1 }, /* 12 ModelAnimationsAnimationGraphWeaponType */
	{ 46, 1 }, /* 13 ModelAnimationsAnimationGraphWeaponAnimations */
	{ 47, 2 }, /* 14 ModelAnimationsAnimationGraphVehicleAnimations */
	{ 49, 1 }, /* 15 ModelAnimationsDeviceAnimations */
	{ 50, 1 }, /* 16 ModelAnimationsAnimationGraphFirstPersonWeaponAnimations */
	{ 51, 1 }, /* 17 ModelAnimationsAnimationGraphSoundReference */
	{ 52, 3 }, /* 18 ModelAnimationsAnimation */
	{ 55, 23 }, /* 19 Biped */
	{ 78, 1 }, /* 20 ObjectAttachment */
	{ 79, 1 }, /* 21 ObjectWidget */
	{ 80, 1 }, /* 22 ObjectChangeColors */
	{ 81, 1 }, /* 23 UnitCameraTrack */
	{ 82, 1 }, /* 24 UnitUnitHudInterface */
	{ 83, 1 }, /* 25 UnitDialogueVariant */
	{ 84, 1 }, /* 26 UnitWeapon */
	{ 85, 3 }, /* 27 UnitSeat */
	{ 88, 4 }, /* 28 Bitmap */
	{ 92, 1 }, /* 29 BitmapGroupSequence */
	{ 93, 1 }, /* 30 BitmapData */
	{ 94, 13 }, /* 31 ModelCollisionGeometry */
	{ 107, 2 }, /* 32 ModelCollisionGeometryRegion */
	{ 109, 1 }, /* 33 ModelCollisionGeometryNode */
	{ 110, 8 }, /* 34 ModelCollisionGeometryBSP */
	{ 118, 1 }, /* 35 ColorTable */
	{ 119, 3 }, /* 36 Contrail */
	{ 122, 1 }, /* 37 ContrailPointState */
	{ 123, 21 }, /* 38 DeviceControl */
	{ 144, 2 }, /* 39 Decal */
	{ 146, 2 }, /* 40 InputDeviceDefaults */
	{ 148, 18 }, /* 41 Device */
	{ 166, 2 }, /* 42 DetailObjectCollection */
	{ 168, 2 }, /* 43 Effect */
	{ 170, 2 }, /* 44 EffectEvent */
	{ 172, 1 }, /* 45 EffectPart */
	{ 173, 1 }, /* 46 EffectParticle */
	{ 174, 3 }, /* 47 Lightning */
	{ 177, 1 }, /* 48 LightningShader */
	{ 178, 16 }, /* 49 Equipment */
	{ 194, 4 }, /* 50 Flag */
	{ 198, 3 }, /* 51 Fog */
	{ 201, 7 }, /* 52 Font */
	{ 208, 1 }, /* 53 FontCharacterTables */
	{ 209, 1 }, /* 54 MaterialEffects */
	{ 210, 1 }, /* 55 MaterialEffectsMaterialEffect */
	{ 211, 2 }, /* 56 MaterialEffectsMaterialEffectMaterial */
	{ 213, 15 }, /* 57 Garbage */
	{ 228, 1 }, /* 58 Glow */
	{ 229, 7 }, /* 59 GrenadeHUDInterface */
	{ 236, 4 }, /* 60 HUDInterfaceMultitextureOverlay */
	{ 240, 1 }, /* 61 GrenadeHUDInterfaceSound */
	{ 241, 3 }, /* 62 HUDMessageText */
	{ 244, 1 }, /* 63 HUDNumber */
	{ 245, 14 }, /* 64 HUDGlobals */
	{ 259, 2 }, /* 65 HUDGlobalsAnniversaryRemap */
	{ 261, 1 }, /* 66 HUDGlobalsAnniversaryRemapTarget */
	{ 262, 15 }, /* 67 Item */
	{ 277, 1 }, /* 68 ItemCollection */
	{ 278, 1 }, /* 69 ItemCollectionPermutation */
	{ 279, 1 }, /* 70 DamageEffect */
	{ 280, 2 }, /* 71 LensFlare */
	{ 282, 18 }, /* 72 DeviceLightFixture */
	{ 300, 3 }, /* 73 Light */
	{ 303, 3 }, /* 74 SoundLooping */
	{ 306, 5 }, /* 75 SoundLoopingTrack */
	{ 311, 1 }, /* 76 SoundLoopingDetail */
	{ 312, 18 }, /* 77 DeviceMachine */
	{ 330, 15 }, /* 78 Globals */
	{ 345, 1 }, /* 79 GlobalsSound */
	{ 346, 1 }, /* 80 GlobalsCamera */
	{ 347, 1 }, /* 81 GlobalsPlayerControl */
	{ 348, 4 }, /* 82 GlobalsGrenade */
	{ 352, 17 }, /* 83 GlobalsRasterizerData */
	{ 369, 16 }, /* 84 GlobalsInterfaceBitmaps */
	{ 385, 1 }, /* 85 GlobalsWeapon */
	{ 386, 1 }, /* 86 GlobalsCheatPowerup */
	{ 387, 7 }, /* 87 GlobalsMultiplayerInformation */
	{ 394, 1 }, /* 88 GlobalsVehicle */
	{ 395, 2 }, /* 89 GlobalsPlayerInformation */
	{ 397, 6 }, /* 90 GlobalsFirstPersonInterface */
	{ 403, 6 }, /* 91 GlobalsFallingDamage */
	{ 409, 4 }, /* 92 GlobalsMaterial */
	{ 413, 1 }, /* 93 GlobalsBreakableSurfaceParticleEffect */
	{ 414, 3 }, /* 94 Meter */
	{ 417, 2 }, /* 95 LightVolume */
	{ 419, 5 }, /* 96 GBXModel */
	{ 424, 1 }, /* 97 ModelMarker */
	{ 425, 1 }, /* 98 ModelRegion */
	{ 426, 1 }, /* 99 ModelRegionPermutation */
	{ 427, 1 }, /* 100 GBXModelGeometry */
	{ 428, 7 }, /* 101 GBXModelGeometryPart */
	{ 435, 1 }, /* 102 ModelShaderReference */
	{ 436, 5 }, /* 103 Model */
	{ 441, 1 }, /* 104 ModelGeometry */
	{ 442, 7 }, /* 105 ModelGeometryPart */
	{ 449, 1 }, /* 106 MultiplayerScenarioDescription */
	{ 450, 2 }, /* 107 MultiplayerScenarioDescriptionScenarioDescription */
	{ 452, 2 }, /* 108 PreferencesNetworkGame */
	{ 454, 11 }, /* 109 Object */
	{ 465, 6 }, /* 110 Particle */
	{ 471, 3 }, /* 111 ParticleSystem */
	{ 474, 3 }, /* 112 ParticleSystemType */
	{ 477, 1 }, /* 113 ParticleSystemTypeStates */
	{ 478, 4 }, /* 114 ParticleSystemTypeParticleState */
	{ 482, 3 }, /* 115 Physics */
	{ 485, 11 }, /* 116 Placeholder */
	{ 496, 18 }, /* 117 Projectile */
	{ 514, 3 }, /* 118 ProjectileMaterialResponse */
	{ 517, 1 }, /* 119 WeatherParticleSystem */
	{ 518, 3 }, /* 120 WeatherParticleSystemParticleType */
	{ 521, 29 }, /* 121 ScenarioStructureBSP */
	{ 550, 1 }, /* 122 ScenarioStructureBSPCollisionMaterial */
	{ 551, 1 }, /* 123 ScenarioStructureBSPLightmap */
	{ 552, 5 }, /* 124 ScenarioStructureBSPMaterial */
	{ 557, 1 }, /* 125 ScenarioStructureBSPLensFlare */
	{ 558, 5 }, /* 126 ScenarioStructureBSPCluster */
	{ 563, 1 }, /* 127 ScenarioStructureBSPSubcluster */
	{ 564, 2 }, /* 128 ScenarioStructureBSPMirror */
	{ 566, 1 }, /* 129 ScenarioStructureBSPClusterPortal */
	{ 567, 1 }, /* 130 ScenarioStructureBSPFogPlane */
	{ 568, 1 }, /* 131 ScenarioStructureBSPFogPalette */
	{ 569, 2 }, /* 132 ScenarioStructureBSPWeatherPalette */
	{ 571, 1 }, /* 133 ScenarioStructureBSPWeatherPolyhedron */
	{ 572, 1 }, /* 134 ScenarioStructureBSPBackgroundSoundPalette */
	{ 573, 1 }, /* 135 ScenarioStructureBSPSoundEnvironmentPalette */
	{ 574, 4 }, /* 136 ScenarioStructureBSPDetailObjectData */
	{ 578, 2 }, /* 137 ScenarioStructureBSPGlobalMapLeaf */
	{ 580, 1 }, /* 138 ScenarioStructureBSPMapLeafFace */
	{ 581, 1 }, /* 139 ScenarioStructureBSPGlobalLeafPortal */
	{ 582, 11 }, /* 140 Scenery */
	{ 593, 4 }, /* 141 ShaderTransparentChicagoExtended */
	{ 597, 1 }, /* 142 ShaderTransparentExtraLayer */
	{ 598, 1 }, /* 143 ShaderTransparentChicagoMap */
	{ 599, 3 }, /* 144 ShaderTransparentChicago */
	{ 602, 61 }, /* 145 Scenario */
	{ 663, 1 }, /* 146 ScenarioSky */
	{ 664, 1 }, /* 147 ScenarioChildScenario */
	{ 665, 1 }, /* 148 ScenarioEditorComment */
	{ 666, 1 }, /* 149 ScenarioSceneryPalette */
	{ 667, 1 }, /* 150 ScenarioBipedPalette */
	{ 668, 1 }, /* 151 ScenarioVehiclePalette */
	{ 669, 1 }, /* 152 ScenarioEquipmentPalette */
	{ 670, 1 }, /* 153 ScenarioWeaponPalette */
	{ 671, 1 }, /* 154 ScenarioMachinePalette */
	{ 672, 1 }, /* 155 ScenarioControlPalette */
	{ 673, 1 }, /* 156 ScenarioLightFixturePalette */
	{ 674, 1 }, /* 157 ScenarioSoundSceneryPalette */
	{ 675, 2 }, /* 158 ScenarioPlayerStartingProfile */
	{ 677, 1 }, /* 159 ScenarioRecordedAnimation */
	{ 678, 1 }, /* 160 ScenarioNetgameFlags */
	{ 679, 1 }, /* 161 ScenarioNetgameEquipment */
	{ 680, 6 }, /* 162 ScenarioStartingEquipment */
	{ 686, 1 }, /* 163 ScenarioDecalPalette */
	{ 687, 1 }, /* 164 ScenarioDetailObjectCollectionPalette */
	{ 688, 1 }, /* 165 ScenarioActorPalette */
	{ 689, 4 }, /* 166 ScenarioEncounter */
	{ 693, 2 }, /* 167 ScenarioSquad */
	{ 695, 2 }, /* 168 ScenarioCommandList */
	{ 697, 1 }, /* 169 ScenarioAIAnimationReference */
	{ 698, 2 }, /* 170 ScenarioAIConversation */
	{ 700, 6 }, /* 171 ScenarioAIConversationLine */
	{ 706, 1 }, /* 172 ScenarioScript */
	{ 707, 1 }, /* 173 ScenarioReference */
	{ 708, 1 }, /* 174 ScenarioSourceFile */
	{ 709, 2 }, /* 175 ScenarioBSP */
	{ 711, 8 }, /* 176 ShaderEnvironment */
	{ 719, 7 }, /* 177 ShaderTransparentGlass */
	{ 726, 6 }, /* 178 Sky */
	{ 732, 1 }, /* 179 SkyLight */
	{ 733, 1 }, /* 180 ShaderTransparentMeter */
	{ 734, 2 }, /* 181 Sound */
	{ 736, 1 }, /* 182 SoundPitchRange */
	{ 737, 3 }, /* 183 SoundPermutation */
	{ 740, 4 }, /* 184 ShaderModel */
	{ 744, 4 }, /* 185 ShaderTransparentGeneric */
	{ 748, 1 }, /* 186 ShaderTransparentGenericMap */
	{ 749, 2 }, /* 187 ShaderTransparentPlasma */
	{ 751, 11 }, /* 188 SoundScenery */
	{ 762, 1 }, /* 189 StringList */
	{ 763, 1 }, /* 190 StringListString */
	{ 764, 4 }, /* 191 ShaderTransparentWater */
	{ 768, 1 }, /* 192 TagCollection */
	{ 769, 1 }, /* 193 TagCollectionTag */
	{ 770, 1 }, /* 194 CameraTrack */
	{ 771, 166 }, /* 195 Dialogue */
	{ 937, 15 }, /* 196 UnitHUDInterface */
	{ 952, 2 }, /* 197 UnitHUDInterfaceAuxiliaryOverlay */
	{ 954, 1 }, /* 198 UnitHUDInterfaceHUDSound */
	{ 955, 3 }, /* 199 UnitHUDInterfaceAuxiliaryPanel */
	{ 958, 20 }, /* 200 Unit */
	{ 978, 1 }, /* 201 UnicodeStringList */
	{ 979, 1 }, /* 202 UnicodeStringListString */
	{ 980, 4 }, /* 203 VirtualKeyboard */
	{ 984, 4 }, /* 204 VirtualKeyboardVirtualKey */
	{ 988, 24 }, /* 205 Vehicle */
	{ 1012, 32 }, /* 206 Weapon */
	{ 1044, 3 }, /* 207 WeaponMagazine */
	{ 1047, 1 }, /* 208 WeaponMagazineObject */
	{ 1048, 3 }, /* 209 WeaponTrigger */
	{ 1051, 6 }, /* 210 WeaponTriggerFiringEffect */
	{ 1057, 7 }, /* 211 WeaponHUDInterface */
	{ 1064, 2 }, /* 212 WeaponHUDInterfaceStaticElement */
	{ 1066, 1 }, /* 213 WeaponHUDInterfaceMeter */
	{ 1067, 2 }, /* 214 WeaponHUDInterfaceCrosshair */
	{ 1069, 2 }, /* 215 WeaponHUDInterfaceOverlayElement */
	{ 1071, 2 }, /* 216 WeaponHUDInterfaceScreenEffect */
};

static const struct tag_layout_group tag_layout_groups[] = {
	{ 0x44654C61UL, 0 }, /* DeLa UIWidgetDefinition */
	{ 0x536F756CUL, 4 }, /* Soul UIWidgetCollection */
	{ 0x61637472UL, 6 }, /* actr Actor */
	{ 0x61637476UL, 7 }, /* actv ActorVariant */
	{ 0x616E7421UL, 8 }, /* ant! Antenna */
	{ 0x616E7472UL, 9 }, /* antr ModelAnimations */
	{ 0x62697064UL, 19 }, /* bipd Biped */
	{ 0x6269746DUL, 28 }, /* bitm Bitmap */
	{ 0x626F6F6DUL, 65535 }, /* boom Spheroid */
	{ 0x63646D67UL, 65535 }, /* cdmg ContinuousDamageEffect */
	{ 0x636F6C6CUL, 31 }, /* coll ModelCollisionGeometry */
	{ 0x636F6C6FUL, 35 }, /* colo ColorTable */
	{ 0x636F6E74UL, 36 }, /* cont Contrail */
	{ 0x6374726CUL, 38 }, /* ctrl DeviceControl */
	{ 0x64656361UL, 39 }, /* deca Decal */
	{ 0x64657663UL, 40 }, /* devc InputDeviceDefaults */
	{ 0x64657669UL, 41 }, /* devi Device */
	{ 0x646F6263UL, 42 }, /* dobc DetailObjectCollection */
	{ 0x65666665UL, 43 }, /* effe Effect */
	{ 0x656C6563UL, 47 }, /* elec Lightning */
	{ 0x65716970UL, 49 }, /* eqip Equipment */
	{ 0x666C6167UL, 50 }, /* flag Flag */
	{ 0x666F6720UL, 51 }, /* fog  Fog */
	{ 0x666F6E74UL, 52 }, /* font Font */
	{ 0x666F6F74UL, 54 }, /* foot MaterialEffects */
	{ 0x67617262UL, 57 }, /* garb Garbage */
	{ 0x676C7721UL, 58 }, /* glw! Glow */
	{ 0x67726869UL, 59 }, /* grhi GrenadeHUDInterface */
	{ 0x686D7420UL, 62 }, /* hmt  HUDMessageText */
	{ 0x68756423UL, 63 }, /* hud# HUDNumber */
	{ 0x68756467UL, 64 }, /* hudg HUDGlobals */
	{ 0x6974656DUL, 67 }, /* item Item */
	{ 0x69746D63UL, 68 }, /* itmc ItemCollection */
	{ 0x6A707421UL, 70 }, /* jpt! DamageEffect */
	{ 0x6C656E73UL, 71 }, /* lens LensFlare */
	{ 0x6C696669UL, 72 }, /* lifi DeviceLightFixture */
	{ 0x6C696768UL, 73 }, /* ligh Light */
	{ 0x6C736E64UL, 74 }, /* lsnd SoundLooping */
	{ 0x6D616368UL, 77 }, /* mach DeviceMachine */
	{ 0x6D617467UL, 78 }, /* matg Globals */
	{ 0x6D657472UL, 94 }, /* metr Meter */
	{ 0x6D677332UL, 95 }, /* mgs2 LightVolume */
	{ 0x6D6F6432UL, 96 }, /* mod2 GBXModel */
	{ 0x6D6F6465UL, 103 }, /* mode Model */
	{ 0x6D706C79UL, 106 }, /* mply MultiplayerScenarioDescription */
	{ 0x6E677072UL, 108 }, /* ngpr PreferencesNetworkGame */
	{ 0x6F626A65UL, 109 }, /* obje Object */
	{ 0x70617274UL, 110 }, /* part Particle */
	{ 0x7063746CUL, 111 }, /* pctl ParticleSystem */
	{ 0x70687973UL, 115 }, /* phys Physics */
	{ 0x706C6163UL, 116 }, /* plac Placeholder */
	{ 0x70706879UL, 65535 }, /* pphy PointPhysics */
	{ 0x70726F6AUL, 117 }, /* proj Projectile */
	{ 0x7261696EUL, 119 }, /* rain WeatherParticleSystem */
	{ 0x73627370UL, 121 }, /* sbsp ScenarioStructureBSP */
	{ 0x7363656EUL, 140 }, /* scen Scenery */
	{ 0x73636578UL, 141 }, /* scex ShaderTransparentChicagoExtended */
	{ 0x73636869UL, 144 }, /* schi ShaderTransparentChicago */
	{ 0x73636E72UL, 145 }, /* scnr Scenario */
	{ 0x73656E76UL, 176 }, /* senv ShaderEnvironment */
	{ 0x73676C61UL, 177 }, /* sgla ShaderTransparentGlass */
	{ 0x73686472UL, 65535 }, /* shdr Shader */
	{ 0x736B7920UL, 178 }, /* sky  Sky */
	{ 0x736D6574UL, 180 }, /* smet ShaderTransparentMeter */
	{ 0x736E6421UL, 181 }, /* snd! Sound */
	{ 0x736E6465UL, 65535 }, /* snde SoundEnvironment */
	{ 0x736F736FUL, 184 }, /* soso ShaderModel */
	{ 0x736F7472UL, 185 }, /* sotr ShaderTransparentGeneric */
	{ 0x73706C61UL, 187 }, /* spla ShaderTransparentPlasma */
	{ 0x73736365UL, 188 }, /* ssce SoundScenery */
	{ 0x73747223UL, 189 }, /* str# StringList */
	{ 0x73776174UL, 191 }, /* swat ShaderTransparentWater */
	{ 0x74616763UL, 192 }, /* tagc TagCollection */
	{ 0x7472616BUL, 194 }, /* trak CameraTrack */
	{ 0x75646C67UL, 195 }, /* udlg Dialogue */
	{ 0x756E6869UL, 196 }, /* unhi UnitHUDInterface */
	{ 0x756E6974UL, 200 }, /* unit Unit */
	{ 0x75737472UL, 201 }, /* ustr UnicodeStringList */
	{ 0x76636B79UL, 203 }, /* vcky VirtualKeyboard */
	{ 0x76656869UL, 205 }, /* vehi Vehicle */
	{ 0x77656170UL, 206 }, /* weap Weapon */
	{ 0x77696E64UL, 65535 }, /* wind Wind */
	{ 0x77706869UL, 211 }, /* wphi WeaponHUDInterface */
};

#define TAG_LAYOUT_STRUCTURE_BSP 121
