"""K2 edit sets for source/ai/ai_debug.c (_ai_debug_render_actor). Each edit is (old, new) with LF newlines and tabs.
Evidence for every edit is on its card (workers/K2/cards/)."""

EDITS = {}

# C1: crouch-line-of-fire block. /Od 0x49c6be..0x49c848 has no named locals here: the strings are unnamed ?: temps
# (-0x1820 friends, -0x1824/-0x1828 player/blocking nested, -0x182c moving-into-fire) consumed directly as csprintf args.
EDITS['E1'] = [(
"""			{
				char const *blocking_type;

				char const *blocking_mode = actor->emotions.crouch_friends_in_line_of_fire ? "friends-blocking" : "";

				if (actor->emotions.crouch_blocking_player_line_of_fire)
				{
					blocking_type = "blocking-player ";
				}
				else
				{
					blocking_type = actor->emotions.crouch_blocking_line_of_fire ? "blocking " : "";
				}

				render_debug_string_at_point(
					TRUE,
					ai_debug_drawstack(),
					csprintf(temporary, "%s%s", blocking_type, blocking_mode),
					global_real_argb_orange);
			}

			/* Moving into fire */

			if (actor->emotions.moving_into_player_line_of_fire ||
				actor->emotions.moving_into_fire_timer > 0)
			{
				char const *string = actor->emotions.moving_into_player_line_of_fire ? "moving-into-fire" : "";

				render_debug_string_at_point(
					TRUE,
					ai_debug_drawstack(),
					csprintf(temporary, "%sforce-stop %d", string, actor->emotions.moving_into_fire_timer),
					global_real_argb_pink);
			}""",
"""			{
				render_debug_string_at_point(
					TRUE,
					ai_debug_drawstack(),
					csprintf(
						temporary,
						"%s%s",
						actor->emotions.crouch_blocking_player_line_of_fire ? "blocking-player " : (actor->emotions.crouch_blocking_line_of_fire ? "blocking " : ""),
						actor->emotions.crouch_friends_in_line_of_fire ? "friends-blocking" : ""),
					global_real_argb_orange);
			}

			/* Moving into fire */

			if (actor->emotions.moving_into_player_line_of_fire ||
				actor->emotions.moving_into_fire_timer > 0)
			{
				render_debug_string_at_point(
					TRUE,
					ai_debug_drawstack(),
					csprintf(
						temporary,
						"%sforce-stop %d",
						actor->emotions.moving_into_player_line_of_fire ? "moving-into-fire" : "",
						actor->emotions.moving_into_fire_timer),
					global_real_argb_pink);
			}""")]

# C2: /Od 0x49c909..0x49c938: blockage_type = MAX(blockage_type, v0) through an unnamed word temp (-0x182e).
EDITS['E2'] = [(
"""						if (blockage_type <= v0)
						{
							blockage_type = v0;
						}""",
"""						blockage_type = MAX(blockage_type, v0);""")]

# C3: /Od 0x49d853..0x49d8ac: encounter_color = active ? green : (outside_current_bsp ? red : purple), through two
# unnamed temps (-0x184c outer, -0x1850 inner) copied into the named encounter_color [ebp-0x13c].
EDITS['E3'] = [(
"""					if (encounter->active)
					{
						encounter_color = global_real_argb_green;
					}
					else if (outside_current_bsp)
					{
						encounter_color = global_real_argb_red;
					}
					else
					{
						encounter_color = global_real_argb_purple;
					}""",
"""					encounter_color = encounter->active ? global_real_argb_green : (outside_current_bsp ? global_real_argb_red : global_real_argb_purple);""")]

# E4..E12: /Od-attested conditional spellings (cards C4..C12); generated by gen_edits_e4_e12.py.
EDITS['E4'] = [('\t\t\t\t\t{\n\t\t\t\t\t\treal_argb_color const *color;\n\n\t\t\t\t\t\tif (prop->ignore)\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\tcolor = global_real_argb_blue;\n\t\t\t\t\t\t}\n\t\t\t\t\t\telse\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\tcolor = prop->preferred_target ? global_real_argb_pink : global_real_argb_red;\n\t\t\t\t\t\t}\n\n\t\t\t\t\t\trender_debug_string_at_point(TRUE, &string_point, csprintf(temporary, "%.2f", prop->target_weight), color);', '\t\t\t\t\t{\n\t\t\t\t\t\trender_debug_string_at_point(\n\t\t\t\t\t\t\tTRUE,\n\t\t\t\t\t\t\t&string_point,\n\t\t\t\t\t\t\tcsprintf(temporary, "%.2f", prop->target_weight),\n\t\t\t\t\t\t\tprop->ignore ? global_real_argb_blue : (prop->preferred_target ? global_real_argb_pink : global_real_argb_red));')]
EDITS['E5'] = [('\t\t\t\t\t\tlong time = prop->last_unreachable_time!=NONE ? game_time_get()-prop->last_unreachable_time : NONE;\n\n\t\t\t\t\t\trender_debug_string_at_point(\n\t\t\t\t\t\t\tTRUE,\n\t\t\t\t\t\t\t&string_point,\n\t\t\t\t\t\t\tcsprintf(temporary, "unr %d %d", prop->unreachable_ticks, time),', '\t\t\t\t\t\trender_debug_string_at_point(\n\t\t\t\t\t\t\tTRUE,\n\t\t\t\t\t\t\t&string_point,\n\t\t\t\t\t\t\tcsprintf(\n\t\t\t\t\t\t\t\ttemporary,\n\t\t\t\t\t\t\t\t"unr %d %d",\n\t\t\t\t\t\t\t\tprop->unreachable_ticks,\n\t\t\t\t\t\t\t\tprop->last_unreachable_time==NONE ? NONE : game_time_get()-prop->last_unreachable_time),')]
EDITS['E6'] = [('\t\t\t\tlong time = prop->last_unreachable_time!=NONE ? game_time_get()-prop->last_unreachable_time : NONE;\n\n\t\t\t\trender_debug_string_at_point(\n\t\t\t\t\tTRUE,\n\t\t\t\t\tai_debug_drawstack(),\n\t\t\t\t\tcsprintf(temporary, "unr %d %d", prop->unreachable_ticks, time),', '\t\t\t\trender_debug_string_at_point(\n\t\t\t\t\tTRUE,\n\t\t\t\t\tai_debug_drawstack(),\n\t\t\t\t\tcsprintf(\n\t\t\t\t\t\ttemporary,\n\t\t\t\t\t\t"unr %d %d",\n\t\t\t\t\t\tprop->unreachable_ticks,\n\t\t\t\t\t\tprop->last_unreachable_time==NONE ? NONE : game_time_get()-prop->last_unreachable_time),')]
EDITS['E7'] = [('\t\t\t\t\t\tchar const *string = actor->state.action_data.guard.cower_panicked ? "panic" : "hide";\n\t\t\t\t\t\trender_debug_string_at_point(\n\t\t\t\t\t\t\tTRUE,\n\t\t\t\t\t\t\tai_debug_drawstack(),\n\t\t\t\t\t\t\tcsprintf(temporary, "%s %d", string, actor->state.action_data.guard.cower_ticks),', '\t\t\t\t\t\trender_debug_string_at_point(\n\t\t\t\t\t\t\tTRUE,\n\t\t\t\t\t\t\tai_debug_drawstack(),\n\t\t\t\t\t\t\tcsprintf(\n\t\t\t\t\t\t\t\ttemporary,\n\t\t\t\t\t\t\t\t"%s %d",\n\t\t\t\t\t\t\t\tactor->state.action_data.guard.cower_panicked ? "panic" : "hide",\n\t\t\t\t\t\t\t\tactor->state.action_data.guard.cower_ticks),')]
EDITS['E8'] = [('\t\t\t\tchar const *string = actor_move_animation_busy(actor_index) ? "busy " : "";\n\t\t\t\t\n\t\t\t\trender_debug_string_at_point(\n\t\t\t\t\tTRUE,\n\t\t\t\t\tai_debug_drawstack(), \n\t\t\t\t\tcsprintf(\n\t\t\t\t\t\ttemporary,\n\t\t\t\t\t\t"%srof %.1f err %.1f dmg %.1f blk %d",\n\t\t\t\t\t\tstring,', '\t\t\t\trender_debug_string_at_point(\n\t\t\t\t\tTRUE,\n\t\t\t\t\tai_debug_drawstack(), \n\t\t\t\t\tcsprintf(\n\t\t\t\t\t\ttemporary,\n\t\t\t\t\t\t"%srof %.1f err %.1f dmg %.1f blk %d",\n\t\t\t\t\t\tactor_move_animation_busy(actor_index) ? "busy " : "",')]
EDITS['E9'] = [('\t\t\t\treal damage = unit==NULL ? 0.f : unit->object.current_body_damage;\n\t\t\t\tchar const *string = actor->meta.unit_index==NONE || !unit_is_busy(actor->meta.unit_index) ? "not-" : "";\n\n\t\t\t\trender_debug_string_at_point(\n\t\t\t\t\tTRUE,\n\t\t\t\t\tai_debug_drawstack(),\n\t\t\t\t\tcsprintf(temporary, "trying: %sbusy dmg %.1f", string, damage),', '\t\t\t\trender_debug_string_at_point(\n\t\t\t\t\tTRUE,\n\t\t\t\t\tai_debug_drawstack(),\n\t\t\t\t\tcsprintf(\n\t\t\t\t\t\ttemporary,\n\t\t\t\t\t\t"trying: %sbusy dmg %.1f",\n\t\t\t\t\t\tactor->meta.unit_index!=NONE && unit_is_busy(actor->meta.unit_index) ? "" : "not-",\n\t\t\t\t\t\tunit==NULL ? 0.f : unit->object.current_body_damage),')]
EDITS['E10'] = [('@@TWICE@@\t\t\t\tchar const *string = actor->danger_zone.projectile.time_until_explosion==NONE ?\n\t\t\t\t\t"NONE" :\n\t\t\t\t\tcsprintf(temporary, "%d", actor->danger_zone.projectile.time_until_explosion);\n\n\t\t\t\trender_debug_string_at_point(\n\t\t\t\t\tTRUE,\n\t\t\t\t\t&actor->danger_zone.position,\n\t\t\t\t\tstring,\n\t\t\t\t\tcolor);', '\t\t\t\trender_debug_string_at_point(\n\t\t\t\t\tTRUE,\n\t\t\t\t\t&actor->danger_zone.position,\n\t\t\t\t\tactor->danger_zone.projectile.time_until_explosion==NONE ?\n\t\t\t\t\t\t"NONE" :\n\t\t\t\t\t\tcsprintf(temporary, "%d", actor->danger_zone.projectile.time_until_explosion),\n\t\t\t\t\tcolor);')]
EDITS['E11'] = [('\t\t\treal_argb_color const *color;\n\n\t\t\tif (actor->danger_zone.currently_perceived)\n\t\t\t{\n\t\t\t\tif (actor->danger_zone.acknowledgement_timer>0)\n\t\t\t\t{\n\t\t\t\t\tcolor = global_real_argb_white;\n\t\t\t\t}\n\t\t\t\telse\n\t\t\t\t{\n\t\t\t\t\tif (actor->danger_zone.noticed_danger)\n\t\t\t\t\t{\n\t\t\t\t\t\tcolor = global_real_argb_yellow;\n\t\t\t\t\t}\n\t\t\t\t\telse\n\t\t\t\t\t{\n\t\t\t\t\t\tcolor = global_real_argb_blue;\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t\telse\n\t\t\t{\n\t\t\t\tcolor = global_real_argb_darkgreen;\n\t\t\t}', '\t\t\treal_argb_color const *color = actor->danger_zone.currently_perceived ?\n\t\t\t\t(actor->danger_zone.acknowledgement_timer>0 ? global_real_argb_white : (actor->danger_zone.noticed_danger ? global_real_argb_yellow : global_real_argb_blue)) :\n\t\t\t\tglobal_real_argb_darkgreen;')]
EDITS['E12'] = [('\t\t\t\treal_argb_color const *color;\n\t\t\t\treal_point3d offset_point;\n\n\t\t\t\tif (actor->control.path.at_destination)\n\t\t\t\t{\n\t\t\t\t\tcolor = global_real_argb_yellow;\n\t\t\t\t}\n\t\t\t\telse\n\t\t\t\t{\n\t\t\t\t\tcolor = actor->control.path.path.steps_finish_path ? global_real_argb_pink : global_real_argb_purple;\n\t\t\t\t}\n', '\t\t\t\treal_argb_color const *color = actor->control.path.at_destination ? global_real_argb_yellow : (actor->control.path.path.steps_finish_path ? global_real_argb_pink : global_real_argb_purple);\n\t\t\t\treal_point3d offset_point;\n')]

# E13 (hygiene): the fixed-crouch-facing block declares `char const *string;` and never uses it (C4101 at /W3). The
# /Od build has no slot for it. Unreferenced locals never enter the C2 symbol pool (S3-2), so removal is expected inert.
EDITS['E13'] = [("""			{
				char const *string;

				if (actor->control.desire_stationary_facing)""",
"""			{
				if (actor->control.desire_stationary_facing)""")]

# E14: vehicle-avoidance second cross. /Od 0x4a2a4b..0x4a2abb: p1 = intersect_point; p0 = p1; then p0.x -= 0.2f and
# p1.x += 0.2f through their own cells (the same pattern the first and third crosses of this block already use).
EDITS['E14'] = [("""			p1 = p2;
			p0 = p2;

			p0.x = p2.x - 0.2f;
			p1.x = p2.x + 0.2f;""",
"""			p1 = p2;
			p0 = p1;

			p0.x = p0.x - 0.2f;
			p1.x = p1.x + 0.2f;""")]
