/*
XDK_PDB.H

The Xbox SDK types, enumerations and function prototypes the game and the
platform layer use, as the January build's debug information
(cachebeta.pdb) records them. Generated by tools/xdk_headers.py from the
names in pdb_names.txt: do not edit, regenerate (see README.md).
*/

#ifndef HALO_XDK_PDB_H
#define HALO_XDK_PDB_H

/* ---------- enumerations */

enum PS_CHANNEL {
    PS_CHANNEL_RGB = 0,
    PS_CHANNEL_BLUE = 0,
    PS_CHANNEL_ALPHA = 16,
};

enum PS_COMBINERCOUNTFLAGS {
    PS_COMBINERCOUNT_MUX_LSB = 0,
    PS_COMBINERCOUNT_MUX_MSB = 1,
    PS_COMBINERCOUNT_SAME_C0 = 0,
    PS_COMBINERCOUNT_UNIQUE_C0 = 16,
    PS_COMBINERCOUNT_SAME_C1 = 0,
    PS_COMBINERCOUNT_UNIQUE_C1 = 256,
};

enum PS_COMBINEROUTPUT {
    PS_COMBINEROUTPUT_IDENTITY = 0,
    PS_COMBINEROUTPUT_BIAS = 8,
    PS_COMBINEROUTPUT_SHIFTLEFT_1 = 16,
    PS_COMBINEROUTPUT_SHIFTLEFT_1_BIAS = 24,
    PS_COMBINEROUTPUT_SHIFTLEFT_2 = 32,
    PS_COMBINEROUTPUT_SHIFTRIGHT_1 = 48,
    PS_COMBINEROUTPUT_AB_BLUE_TO_ALPHA = 128,
    PS_COMBINEROUTPUT_CD_BLUE_TO_ALPHA = 64,
    PS_COMBINEROUTPUT_AB_MULTIPLY = 0,
    PS_COMBINEROUTPUT_AB_DOT_PRODUCT = 2,
    PS_COMBINEROUTPUT_CD_MULTIPLY = 0,
    PS_COMBINEROUTPUT_CD_DOT_PRODUCT = 1,
    PS_COMBINEROUTPUT_AB_CD_SUM = 0,
    PS_COMBINEROUTPUT_AB_CD_MUX = 4,
};

enum PS_DOTMAPPING {
    PS_DOTMAPPING_ZERO_TO_ONE = 0,
    PS_DOTMAPPING_MINUS1_TO_1_D3D = 1,
    PS_DOTMAPPING_MINUS1_TO_1_GL = 2,
    PS_DOTMAPPING_MINUS1_TO_1 = 3,
    PS_DOTMAPPING_HILO_1 = 4,
    PS_DOTMAPPING_HILO_HEMISPHERE_D3D = 5,
    PS_DOTMAPPING_HILO_HEMISPHERE_GL = 6,
    PS_DOTMAPPING_HILO_HEMISPHERE = 7,
};

enum PS_INPUTMAPPING {
    PS_INPUTMAPPING_UNSIGNED_IDENTITY = 0,
    PS_INPUTMAPPING_UNSIGNED_INVERT = 32,
    PS_INPUTMAPPING_EXPAND_NORMAL = 64,
    PS_INPUTMAPPING_EXPAND_NEGATE = 96,
    PS_INPUTMAPPING_HALFBIAS_NORMAL = 128,
    PS_INPUTMAPPING_HALFBIAS_NEGATE = 160,
    PS_INPUTMAPPING_SIGNED_IDENTITY = 192,
    PS_INPUTMAPPING_SIGNED_NEGATE = 224,
};

enum PS_REGISTER {
    PS_REGISTER_ZERO = 0,
    PS_REGISTER_DISCARD = 0,
    PS_REGISTER_C0 = 1,
    PS_REGISTER_C1 = 2,
    PS_REGISTER_FOG = 3,
    PS_REGISTER_V0 = 4,
    PS_REGISTER_V1 = 5,
    PS_REGISTER_T0 = 8,
    PS_REGISTER_T1 = 9,
    PS_REGISTER_T2 = 10,
    PS_REGISTER_T3 = 11,
    PS_REGISTER_R0 = 12,
    PS_REGISTER_R1 = 13,
    PS_REGISTER_V1R0_SUM = 14,
    PS_REGISTER_EF_PROD = 15,
    PS_REGISTER_ONE = 32,
    PS_REGISTER_NEGATIVE_ONE = 64,
    PS_REGISTER_ONE_HALF = 160,
    PS_REGISTER_NEGATIVE_ONE_HALF = 128,
};

enum PS_TEXTUREMODES {
    PS_TEXTUREMODES_NONE = 0,
    PS_TEXTUREMODES_PROJECT2D = 1,
    PS_TEXTUREMODES_PROJECT3D = 2,
    PS_TEXTUREMODES_CUBEMAP = 3,
    PS_TEXTUREMODES_PASSTHRU = 4,
    PS_TEXTUREMODES_CLIPPLANE = 5,
    PS_TEXTUREMODES_BUMPENVMAP = 6,
    PS_TEXTUREMODES_BUMPENVMAP_LUM = 7,
    PS_TEXTUREMODES_BRDF = 8,
    PS_TEXTUREMODES_DOT_ST = 9,
    PS_TEXTUREMODES_DOT_ZW = 10,
    PS_TEXTUREMODES_DOT_RFLCT_DIFF = 11,
    PS_TEXTUREMODES_DOT_RFLCT_SPEC = 12,
    PS_TEXTUREMODES_DOT_STR_3D = 13,
    PS_TEXTUREMODES_DOT_STR_CUBE = 14,
    PS_TEXTUREMODES_DPNDNT_AR = 15,
    PS_TEXTUREMODES_DPNDNT_GB = 16,
    PS_TEXTUREMODES_DOTPRODUCT = 17,
    PS_TEXTUREMODES_DOT_RFLCT_SPEC_CONST = 18,
};

enum _D3DBLEND {
    D3DBLEND_ZERO = 0,
    D3DBLEND_ONE = 1,
    D3DBLEND_SRCCOLOR = 768,
    D3DBLEND_INVSRCCOLOR = 769,
    D3DBLEND_SRCALPHA = 770,
    D3DBLEND_INVSRCALPHA = 771,
    D3DBLEND_DESTALPHA = 772,
    D3DBLEND_INVDESTALPHA = 773,
    D3DBLEND_DESTCOLOR = 774,
    D3DBLEND_INVDESTCOLOR = 775,
    D3DBLEND_SRCALPHASAT = 776,
    D3DBLEND_CONSTANTCOLOR = 32769,
    D3DBLEND_INVCONSTANTCOLOR = 32770,
    D3DBLEND_CONSTANTALPHA = 32771,
    D3DBLEND_INVCONSTANTALPHA = 32772,
    D3DBLEND_FORCE_DWORD = 0x7fffffff,
};

enum _D3DBLENDOP {
    D3DBLENDOP_ADD = 32774,
    D3DBLENDOP_SUBTRACT = 32778,
    D3DBLENDOP_REVSUBTRACT = 32779,
    D3DBLENDOP_MIN = 32775,
    D3DBLENDOP_MAX = 32776,
    D3DBLENDOP_ADDSIGNED = 61446,
    D3DBLENDOP_REVSUBTRACTSIGNED = 61445,
    D3DBLENDOP_FORCE_DWORD = 0x7fffffff,
};

enum _D3DCALLBACKTYPE {
    D3DCALLBACK_READ = 0,
    D3DCALLBACK_WRITE = 1,
    D3DCALLBACKTYPE_FORCE_DWORD = 0x7fffffff,
};

enum _D3DCMPFUNC {
    D3DCMP_NEVER = 512,
    D3DCMP_LESS = 513,
    D3DCMP_EQUAL = 514,
    D3DCMP_LESSEQUAL = 515,
    D3DCMP_GREATER = 516,
    D3DCMP_NOTEQUAL = 517,
    D3DCMP_GREATEREQUAL = 518,
    D3DCMP_ALWAYS = 519,
    D3DCMP_FORCE_DWORD = 0x7fffffff,
};

enum _D3DCUBEMAP_FACES {
    D3DCUBEMAP_FACE_POSITIVE_X = 0,
    D3DCUBEMAP_FACE_NEGATIVE_X = 1,
    D3DCUBEMAP_FACE_POSITIVE_Y = 2,
    D3DCUBEMAP_FACE_NEGATIVE_Y = 3,
    D3DCUBEMAP_FACE_POSITIVE_Z = 4,
    D3DCUBEMAP_FACE_NEGATIVE_Z = 5,
    D3DCUBEMAP_FACE_FORCE_DWORD = 0x7fffffff,
};

enum _D3DCULL {
    D3DCULL_NONE = 0,
    D3DCULL_CW = 2304,
    D3DCULL_CCW = 2305,
    D3DCULL_FORCE_DWORD = 0x7fffffff,
};

enum _D3DDEVTYPE {
    D3DDEVTYPE_HAL = 1,
    D3DDEVTYPE_REF = 2,
    D3DDEVTYPE_SW = 3,
    D3DDEVTYPE_FORCE_DWORD = 0x7fffffff,
};

enum _D3DFILLMODE {
    D3DFILL_POINT = 6912,
    D3DFILL_WIREFRAME = 6913,
    D3DFILL_SOLID = 6914,
    D3DFILL_FORCE_DWORD = 0x7fffffff,
};

enum _D3DFOGMODE {
    D3DFOG_NONE = 0,
    D3DFOG_EXP = 1,
    D3DFOG_EXP2 = 2,
    D3DFOG_LINEAR = 3,
    D3DFOG_FORCE_DWORD = 0x7fffffff,
};

enum _D3DFORMAT {
    D3DFMT_UNKNOWN = -1,
    D3DFMT_A8R8G8B8 = 6,
    D3DFMT_X8R8G8B8 = 7,
    D3DFMT_R5G6B5 = 5,
    D3DFMT_R6G5B5 = 39,
    D3DFMT_X1R5G5B5 = 3,
    D3DFMT_A1R5G5B5 = 2,
    D3DFMT_A4R4G4B4 = 4,
    D3DFMT_A8 = 25,
    D3DFMT_A8B8G8R8 = 58,
    D3DFMT_B8G8R8A8 = 59,
    D3DFMT_R4G4B4A4 = 57,
    D3DFMT_R5G5B5A1 = 56,
    D3DFMT_R8G8B8A8 = 60,
    D3DFMT_R8B8 = 41,
    D3DFMT_G8B8 = 40,
    D3DFMT_P8 = 11,
    D3DFMT_L8 = 0,
    D3DFMT_A8L8 = 26,
    D3DFMT_AL8 = 1,
    D3DFMT_L16 = 50,
    D3DFMT_V8U8 = 40,
    D3DFMT_L6V5U5 = 39,
    D3DFMT_X8L8V8U8 = 7,
    D3DFMT_Q8W8V8U8 = 58,
    D3DFMT_V16U16 = 51,
    D3DFMT_D16_LOCKABLE = 44,
    D3DFMT_D16 = 44,
    D3DFMT_D24S8 = 42,
    D3DFMT_F16 = 45,
    D3DFMT_F24S8 = 43,
    D3DFMT_YUY2 = 36,
    D3DFMT_UYVY = 37,
    D3DFMT_DXT1 = 12,
    D3DFMT_DXT2 = 14,
    D3DFMT_DXT3 = 14,
    D3DFMT_DXT4 = 15,
    D3DFMT_DXT5 = 15,
    D3DFMT_LIN_A1R5G5B5 = 16,
    D3DFMT_LIN_A4R4G4B4 = 29,
    D3DFMT_LIN_A8 = 31,
    D3DFMT_LIN_A8B8G8R8 = 63,
    D3DFMT_LIN_A8R8G8B8 = 18,
    D3DFMT_LIN_B8G8R8A8 = 64,
    D3DFMT_LIN_G8B8 = 23,
    D3DFMT_LIN_R4G4B4A4 = 62,
    D3DFMT_LIN_R5G5B5A1 = 61,
    D3DFMT_LIN_R5G6B5 = 17,
    D3DFMT_LIN_R6G5B5 = 55,
    D3DFMT_LIN_R8B8 = 22,
    D3DFMT_LIN_R8G8B8A8 = 65,
    D3DFMT_LIN_X1R5G5B5 = 28,
    D3DFMT_LIN_X8R8G8B8 = 30,
    D3DFMT_LIN_A8L8 = 32,
    D3DFMT_LIN_AL8 = 27,
    D3DFMT_LIN_L16 = 53,
    D3DFMT_LIN_L8 = 19,
    D3DFMT_LIN_V16U16 = 54,
    D3DFMT_LIN_V8U8 = 23,
    D3DFMT_LIN_L6V5U5 = 55,
    D3DFMT_LIN_X8L8V8U8 = 30,
    D3DFMT_LIN_Q8W8V8U8 = 18,
    D3DFMT_LIN_D24S8 = 46,
    D3DFMT_LIN_F24S8 = 47,
    D3DFMT_LIN_D16 = 48,
    D3DFMT_LIN_F16 = 49,
    D3DFMT_VERTEXDATA = 100,
    D3DFMT_INDEX16 = 101,
    D3DFMT_FORCE_DWORD = 0x7fffffff,
};

enum _D3DFRONT {
    D3DFRONT_CW = 2304,
    D3DFRONT_CCW = 2305,
    D3DFRONT_FORCE_DWORD = 0x7fffffff,
};

enum _D3DPALETTESIZE {
    D3DPALETTE_256 = 0,
    D3DPALETTE_128 = 1,
    D3DPALETTE_64 = 2,
    D3DPALETTE_32 = 3,
    D3DPALETTE_MAX = 4,
    D3DPALETTE_FORCE_DWORD = 0x7fffffff,
};

enum _D3DPRIMITIVETYPE {
    D3DPT_POINTLIST = 1,
    D3DPT_LINELIST = 2,
    D3DPT_LINELOOP = 3,
    D3DPT_LINESTRIP = 4,
    D3DPT_TRIANGLELIST = 5,
    D3DPT_TRIANGLESTRIP = 6,
    D3DPT_TRIANGLEFAN = 7,
    D3DPT_QUADLIST = 8,
    D3DPT_QUADSTRIP = 9,
    D3DPT_POLYGON = 10,
    D3DPT_MAX = 11,
    D3DPT_FORCE_DWORD = 0x7fffffff,
};

enum _D3DRENDERSTATETYPE {
    D3DRS_PS_MIN = 0,
    D3DRS_PSALPHAINPUTS0 = 0,
    D3DRS_PSALPHAINPUTS1 = 1,
    D3DRS_PSALPHAINPUTS2 = 2,
    D3DRS_PSALPHAINPUTS3 = 3,
    D3DRS_PSALPHAINPUTS4 = 4,
    D3DRS_PSALPHAINPUTS5 = 5,
    D3DRS_PSALPHAINPUTS6 = 6,
    D3DRS_PSALPHAINPUTS7 = 7,
    D3DRS_PSFINALCOMBINERINPUTSABCD = 8,
    D3DRS_PSFINALCOMBINERINPUTSEFG = 9,
    D3DRS_PSCONSTANT0_0 = 10,
    D3DRS_PSCONSTANT0_1 = 11,
    D3DRS_PSCONSTANT0_2 = 12,
    D3DRS_PSCONSTANT0_3 = 13,
    D3DRS_PSCONSTANT0_4 = 14,
    D3DRS_PSCONSTANT0_5 = 15,
    D3DRS_PSCONSTANT0_6 = 16,
    D3DRS_PSCONSTANT0_7 = 17,
    D3DRS_PSCONSTANT1_0 = 18,
    D3DRS_PSCONSTANT1_1 = 19,
    D3DRS_PSCONSTANT1_2 = 20,
    D3DRS_PSCONSTANT1_3 = 21,
    D3DRS_PSCONSTANT1_4 = 22,
    D3DRS_PSCONSTANT1_5 = 23,
    D3DRS_PSCONSTANT1_6 = 24,
    D3DRS_PSCONSTANT1_7 = 25,
    D3DRS_PSALPHAOUTPUTS0 = 26,
    D3DRS_PSALPHAOUTPUTS1 = 27,
    D3DRS_PSALPHAOUTPUTS2 = 28,
    D3DRS_PSALPHAOUTPUTS3 = 29,
    D3DRS_PSALPHAOUTPUTS4 = 30,
    D3DRS_PSALPHAOUTPUTS5 = 31,
    D3DRS_PSALPHAOUTPUTS6 = 32,
    D3DRS_PSALPHAOUTPUTS7 = 33,
    D3DRS_PSRGBINPUTS0 = 34,
    D3DRS_PSRGBINPUTS1 = 35,
    D3DRS_PSRGBINPUTS2 = 36,
    D3DRS_PSRGBINPUTS3 = 37,
    D3DRS_PSRGBINPUTS4 = 38,
    D3DRS_PSRGBINPUTS5 = 39,
    D3DRS_PSRGBINPUTS6 = 40,
    D3DRS_PSRGBINPUTS7 = 41,
    D3DRS_PSCOMPAREMODE = 42,
    D3DRS_PSFINALCOMBINERCONSTANT0 = 43,
    D3DRS_PSFINALCOMBINERCONSTANT1 = 44,
    D3DRS_PSRGBOUTPUTS0 = 45,
    D3DRS_PSRGBOUTPUTS1 = 46,
    D3DRS_PSRGBOUTPUTS2 = 47,
    D3DRS_PSRGBOUTPUTS3 = 48,
    D3DRS_PSRGBOUTPUTS4 = 49,
    D3DRS_PSRGBOUTPUTS5 = 50,
    D3DRS_PSRGBOUTPUTS6 = 51,
    D3DRS_PSRGBOUTPUTS7 = 52,
    D3DRS_PSCOMBINERCOUNT = 53,
    D3DRS_PSDOTMAPPING = 55,
    D3DRS_PSINPUTTEXTURE = 56,
    D3DRS_PS_MAX = 57,
    D3DRS_ZFUNC = 57,
    D3DRS_ALPHAFUNC = 58,
    D3DRS_ALPHABLENDENABLE = 59,
    D3DRS_ALPHATESTENABLE = 60,
    D3DRS_ALPHAREF = 61,
    D3DRS_SRCBLEND = 62,
    D3DRS_DESTBLEND = 63,
    D3DRS_ZWRITEENABLE = 64,
    D3DRS_DITHERENABLE = 65,
    D3DRS_SHADEMODE = 66,
    D3DRS_COLORWRITEENABLE = 67,
    D3DRS_STENCILZFAIL = 68,
    D3DRS_STENCILPASS = 69,
    D3DRS_STENCILFUNC = 70,
    D3DRS_STENCILREF = 71,
    D3DRS_STENCILMASK = 72,
    D3DRS_STENCILWRITEMASK = 73,
    D3DRS_BLENDOP = 74,
    D3DRS_BLENDCOLOR = 75,
    D3DRS_SWATHWIDTH = 76,
    D3DRS_POLYGONOFFSETZSLOPESCALE = 77,
    D3DRS_POLYGONOFFSETZOFFSET = 78,
    D3DRS_POINTOFFSETENABLE = 79,
    D3DRS_WIREFRAMEOFFSETENABLE = 80,
    D3DRS_SOLIDOFFSETENABLE = 81,
    D3DRS_SIMPLE_MAX = 82,
    D3DRS_FOGENABLE = 82,
    D3DRS_FOGTABLEMODE = 83,
    D3DRS_FOGSTART = 84,
    D3DRS_FOGEND = 85,
    D3DRS_FOGDENSITY = 86,
    D3DRS_RANGEFOGENABLE = 87,
    D3DRS_WRAP0 = 88,
    D3DRS_WRAP1 = 89,
    D3DRS_WRAP2 = 90,
    D3DRS_WRAP3 = 91,
    D3DRS_LIGHTING = 92,
    D3DRS_SPECULARENABLE = 93,
    D3DRS_LOCALVIEWER = 94,
    D3DRS_COLORVERTEX = 95,
    D3DRS_BACKSPECULARMATERIALSOURCE = 96,
    D3DRS_BACKDIFFUSEMATERIALSOURCE = 97,
    D3DRS_BACKAMBIENTMATERIALSOURCE = 98,
    D3DRS_BACKEMISSIVEMATERIALSOURCE = 99,
    D3DRS_SPECULARMATERIALSOURCE = 100,
    D3DRS_DIFFUSEMATERIALSOURCE = 101,
    D3DRS_AMBIENTMATERIALSOURCE = 102,
    D3DRS_EMISSIVEMATERIALSOURCE = 103,
    D3DRS_BACKAMBIENT = 104,
    D3DRS_AMBIENT = 105,
    D3DRS_POINTSIZE = 106,
    D3DRS_POINTSIZE_MIN = 107,
    D3DRS_POINTSPRITEENABLE = 108,
    D3DRS_POINTSCALEENABLE = 109,
    D3DRS_POINTSCALE_A = 110,
    D3DRS_POINTSCALE_B = 111,
    D3DRS_POINTSCALE_C = 112,
    D3DRS_POINTSIZE_MAX = 113,
    D3DRS_PATCHEDGESTYLE = 114,
    D3DRS_PATCHSEGMENTS = 115,
    D3DRS_DEFERRED_MAX = 116,
    D3DRS_PSTEXTUREMODES = 116,
    D3DRS_VERTEXBLEND = 117,
    D3DRS_FOGCOLOR = 118,
    D3DRS_FILLMODE = 119,
    D3DRS_BACKFILLMODE = 120,
    D3DRS_TWOSIDEDLIGHTING = 121,
    D3DRS_NORMALIZENORMALS = 122,
    D3DRS_ZENABLE = 123,
    D3DRS_STENCILENABLE = 124,
    D3DRS_STENCILFAIL = 125,
    D3DRS_FRONTFACE = 126,
    D3DRS_CULLMODE = 127,
    D3DRS_TEXTUREFACTOR = 128,
    D3DRS_ZBIAS = 129,
    D3DRS_LOGICOP = 130,
    D3DRS_EDGEANTIALIAS = 131,
    D3DRS_MULTISAMPLEANTIALIAS = 132,
    D3DRS_MULTISAMPLEMASK = 133,
    D3DRS_MULTISAMPLETYPE = 134,
    D3DRS_SHADOWFUNC = 135,
    D3DRS_LINEWIDTH = 136,
    D3DRS_DXT1NOISEENABLE = 137,
    D3DRS_YUVENABLE = 138,
    D3DRS_OCCLUSIONCULLENABLE = 139,
    D3DRS_STENCILCULLENABLE = 140,
    D3DRS_ROPZCMPALWAYSREAD = 141,
    D3DRS_ROPZREAD = 142,
    D3DRS_DONOTCULLUNCOMPRESSED = 143,
    D3DRS_MAX = 144,
    D3DRS_FORCE_DWORD = 0x7fffffff,
};

enum _D3DRESOURCETYPE {
    D3DRTYPE_NONE = 0,
    D3DRTYPE_SURFACE = 1,
    D3DRTYPE_VOLUME = 2,
    D3DRTYPE_TEXTURE = 3,
    D3DRTYPE_VOLUMETEXTURE = 4,
    D3DRTYPE_CUBETEXTURE = 5,
    D3DRTYPE_VERTEXBUFFER = 6,
    D3DRTYPE_INDEXBUFFER = 7,
    D3DRTYPE_PUSHBUFFER = 8,
    D3DRTYPE_PALETTE = 9,
    D3DRTYPE_FIXUP = 10,
    D3DRTYPE_FORCE_DWORD = 0x7fffffff,
};

enum _D3DSTENCILOP {
    D3DSTENCILOP_KEEP = 7680,
    D3DSTENCILOP_ZERO = 0,
    D3DSTENCILOP_REPLACE = 7681,
    D3DSTENCILOP_INCRSAT = 7682,
    D3DSTENCILOP_DECRSAT = 7683,
    D3DSTENCILOP_INVERT = 5386,
    D3DSTENCILOP_INCR = 34055,
    D3DSTENCILOP_DECR = 34056,
    D3DSTENCILOP_FORCE_DWORD = 0x7fffffff,
};

enum _D3DSWAPEFFECT {
    D3DSWAPEFFECT_DISCARD = 1,
    D3DSWAPEFFECT_FLIP = 2,
    D3DSWAPEFFECT_COPY = 3,
    D3DSWAPEFFECT_COPY_VSYNC = 4,
    D3DSWAPEFFECT_FORCE_DWORD = 0x7fffffff,
};

enum _D3DTEXTUREADDRESS {
    D3DTADDRESS_WRAP = 1,
    D3DTADDRESS_MIRROR = 2,
    D3DTADDRESS_CLAMP = 3,
    D3DTADDRESS_BORDER = 4,
    D3DTADDRESS_CLAMPTOEDGE = 5,
    D3DTADDRESS_MAX = 6,
    D3DTADDRESS_FORCE_DWORD = 0x7fffffff,
};

enum _D3DTEXTUREALPHAKILL {
    D3DTALPHAKILL_DISABLE = 0,
    D3DTALPHAKILL_ENABLE = 4,
    D3DTALPHAKILL_FORCE_DWORD = 0x7fffffff,
};

enum _D3DTEXTUREFILTERTYPE {
    D3DTEXF_NONE = 0,
    D3DTEXF_POINT = 1,
    D3DTEXF_LINEAR = 2,
    D3DTEXF_ANISOTROPIC = 3,
    D3DTEXF_QUINCUNX = 4,
    D3DTEXF_GAUSSIANCUBIC = 5,
    D3DTEXF_MAX = 6,
    D3DTEXF_FORCE_DWORD = 0x7fffffff,
};

enum _D3DTEXTURESTAGESTATETYPE {
    D3DTSS_COLOROP = 0,
    D3DTSS_COLORARG0 = 1,
    D3DTSS_COLORARG1 = 2,
    D3DTSS_COLORARG2 = 3,
    D3DTSS_ALPHAOP = 4,
    D3DTSS_ALPHAARG0 = 5,
    D3DTSS_ALPHAARG1 = 6,
    D3DTSS_ALPHAARG2 = 7,
    D3DTSS_RESULTARG = 8,
    D3DTSS_TEXTURETRANSFORMFLAGS = 9,
    D3DTSS_ADDRESSU = 10,
    D3DTSS_ADDRESSV = 11,
    D3DTSS_ADDRESSW = 12,
    D3DTSS_MAGFILTER = 13,
    D3DTSS_MINFILTER = 14,
    D3DTSS_MIPFILTER = 15,
    D3DTSS_MIPMAPLODBIAS = 16,
    D3DTSS_MAXMIPLEVEL = 17,
    D3DTSS_MAXANISOTROPY = 18,
    D3DTSS_COLORKEYOP = 19,
    D3DTSS_COLORSIGN = 20,
    D3DTSS_ALPHAKILL = 21,
    D3DTSS_DEFERRED_MAX = 22,
    D3DTSS_BUMPENVMAT00 = 22,
    D3DTSS_BUMPENVMAT01 = 23,
    D3DTSS_BUMPENVMAT11 = 24,
    D3DTSS_BUMPENVMAT10 = 25,
    D3DTSS_BUMPENVLSCALE = 26,
    D3DTSS_BUMPENVLOFFSET = 27,
    D3DTSS_TEXCOORDINDEX = 28,
    D3DTSS_BORDERCOLOR = 29,
    D3DTSS_COLORKEYCOLOR = 30,
    D3DTSS_MAX = 32,
    D3DTSS_FORCE_DWORD = 0x7fffffff,
};

enum _D3DTRANSFORMSTATETYPE {
    D3DTS_VIEW = 0,
    D3DTS_PROJECTION = 1,
    D3DTS_TEXTURE0 = 2,
    D3DTS_TEXTURE1 = 3,
    D3DTS_TEXTURE2 = 4,
    D3DTS_TEXTURE3 = 5,
    D3DTS_WORLD = 6,
    D3DTS_WORLD1 = 7,
    D3DTS_WORLD2 = 8,
    D3DTS_WORLD3 = 9,
    D3DTS_MAX = 10,
    D3DTS_FORCE_DWORD = 0x7fffffff,
};

enum _D3DVSD_TOKENTYPE {
    D3DVSD_TOKEN_NOP = 0,
    D3DVSD_TOKEN_STREAM = 1,
    D3DVSD_TOKEN_STREAMDATA = 2,
    D3DVSD_TOKEN_TESSELLATOR = 3,
    D3DVSD_TOKEN_CONSTMEM = 4,
    D3DVSD_TOKEN_EXT = 5,
    D3DVSD_TOKEN_END = 7,
    D3DVSD_FORCE_DWORD = 0x7fffffff,
};

enum _D3DZBUFFERTYPE {
    D3DZB_FALSE = 0,
    D3DZB_TRUE = 1,
    D3DZB_USEW = 2,
    D3DZB_FORCE_DWORD = 0x7fffffff,
};

enum _GET_FILEEX_INFO_LEVELS {
    GetFileExInfoStandard = 0,
    GetFileExMaxInfoLevel = 1,
};

/* ---------- structures and unions */

struct D3DBaseTexture;
struct D3DCubeTexture;
struct D3DDevice;
struct D3DIndexBuffer;
struct D3DPalette;
struct D3DResource;
struct D3DSurface;
struct D3DTexture;
struct D3DVertexBuffer;
struct D3DVolumeTexture;
struct D3DXVECTOR4;
struct Direct3D;
struct HINSTANCE__;
struct HWND__;
struct IDirectSound;
struct IDirectSoundBuffer;
struct IDirectSoundStream;
struct IDirectSoundStreamVtbl;
struct IUnknown;
struct WSAData;
struct XNADDR;
struct XNKEY;
struct XNKID;
struct XNetStartupParams;
struct _CONTEXT;
struct _D3DBOX;
struct _D3DCAPS8;
struct _D3DLOCKED_BOX;
struct _D3DLOCKED_RECT;
struct _D3DMATRIX;
struct _D3DPRESENT_PARAMETERS_;
struct _D3DPixelShaderDef;
struct _D3DRECT;
struct _D3DSURFACE_DESC;
struct _D3DVIEWPORT8;
struct _DSBUFFERDESC;
struct _DSCAPS;
struct _DSEFFECTIMAGEDESC;
struct _DSEFFECTIMAGELOC;
struct _DSI3DL2BUFFER;
struct _DSI3DL2LISTENER;
struct _DSI3DL2OBSTRUCTION;
struct _DSI3DL2OCCLUSION;
struct _DSSTREAMDESC;
struct _EXCEPTION_POINTERS;
struct _EXCEPTION_RECORD;
struct _FILETIME;
struct _FLOATING_SAVE_AREA;
struct _GUID;
union _LARGE_INTEGER;
struct _LAUNCH_DATA;
struct _LD_LAUNCH_DASHBOARD;
struct _LIST_ENTRY;
struct _MEMORYSTATUS;
struct _OVERLAPPED;
struct _RTL_CRITICAL_SECTION;
struct _SYSTEMTIME;
union _ULARGE_INTEGER;
struct _WIN32_FILE_ATTRIBUTE_DATA;
struct _WIN32_FIND_DATAA;
struct _XCALCSIG_SIGNATURE;
struct _XDEVICE_PREALLOC_TYPE;
struct _XGAME_FIND_DATA;
struct _XINPUT_DEBUG_KEYQUEUE_PARAMETERS;
struct _XINPUT_DEBUG_KEYSTROKE;
struct _XINPUT_FEEDBACK;
struct _XINPUT_FEEDBACK_HEADER;
struct _XINPUT_GAMEPAD;
struct _XINPUT_POLLING_PARAMETERS;
struct _XINPUT_RUMBLE;
struct _XINPUT_STATE;
struct _XMEDIAINFO;
struct _XMEDIAPACKET;
struct _XPP_DEVICE_TYPE;
struct fd_set;
struct in_addr;
struct sockaddr;
struct sockaddr_in;
struct tWAVEFORMATEX;
struct tagRECT;
struct timeval;
struct xbox_adpcmwaveformat_tag;

#ifdef __cplusplus
struct D3DDevice {};
struct Direct3D {};
struct IDirectSoundBuffer {};
#endif

struct D3DBaseTexture {
    unsigned long Common;
    unsigned long Data;
    unsigned long Lock;
    unsigned long Format;
    unsigned long Size;
};

struct D3DCubeTexture {
    unsigned long Common;
    unsigned long Data;
    unsigned long Lock;
    unsigned long Format;
    unsigned long Size;
};

struct D3DIndexBuffer {
    unsigned long Common;
    unsigned long Data;
    unsigned long Lock;
};

struct D3DPalette {
    unsigned long Common;
    unsigned long Data;
    unsigned long Lock;
};

struct D3DResource {
    unsigned long Common;
    unsigned long Data;
    unsigned long Lock;
};

struct D3DSurface {
    unsigned long Common;
    unsigned long Data;
    unsigned long Lock;
    unsigned long Format;
    unsigned long Size;
    struct D3DBaseTexture *Parent;
};

struct D3DTexture {
    unsigned long Common;
    unsigned long Data;
    unsigned long Lock;
    unsigned long Format;
    unsigned long Size;
};

struct D3DVertexBuffer {
    unsigned long Common;
    unsigned long Data;
    unsigned long Lock;
};

struct D3DVolumeTexture {
    unsigned long Common;
    unsigned long Data;
    unsigned long Lock;
    unsigned long Format;
    unsigned long Size;
};

struct D3DXVECTOR4 {
    float x;
    float y;
    float z;
    float w;
};

struct IDirectSoundStream {
    struct IDirectSoundStreamVtbl *lpVtbl;
};

struct IDirectSoundStreamVtbl {
    unsigned long (__stdcall *AddRef)(struct IDirectSoundStream *);
    unsigned long (__stdcall *Release)(struct IDirectSoundStream *);
    long (__stdcall *GetInfo)(struct IDirectSoundStream *, struct _XMEDIAINFO *);
    long (__stdcall *GetStatus)(struct IDirectSoundStream *, unsigned long *);
    long (__stdcall *Process)(struct IDirectSoundStream *, const struct _XMEDIAPACKET *, const struct _XMEDIAPACKET *);
    long (__stdcall *Discontinuity)(struct IDirectSoundStream *);
    long (__stdcall *Flush)(struct IDirectSoundStream *);
};

struct WSAData {
    unsigned short wVersion;
    unsigned short wHighVersion;
    char szDescription[257];
    char szSystemStatus[129];
    unsigned short iMaxSockets;
    unsigned short iMaxUdpDg;
    char *lpVendorInfo;
};

struct in_addr {
    union {
        struct {
            unsigned char s_b1;
            unsigned char s_b2;
            unsigned char s_b3;
            unsigned char s_b4;
        } S_un_b;
        struct {
            unsigned short s_w1;
            unsigned short s_w2;
        } S_un_w;
        unsigned long S_addr;
    } S_un;
};

struct XNADDR {
    unsigned char bSizeOfStruct;
    unsigned char bFlags;
    unsigned char abEnet[6];
    struct in_addr ina;
};

struct XNKEY {
    unsigned char ab[16];
};

struct XNKID {
    unsigned char ab[8];
};

struct XNetStartupParams {
    unsigned char cfgSizeOfStruct;
    unsigned char cfgFlags;
    unsigned char cfgPrivatePoolSizeInPages;
    unsigned char cfgEnetReceiveQueueLength;
    unsigned char cfgIpFragMaxSimultaneous;
    unsigned char cfgIpFragMaxPacketDiv256;
    unsigned char cfgSockMaxSockets;
    unsigned char cfgSockDefaultRecvBufsizeInK;
    unsigned char cfgSockDefaultSendBufsizeInK;
    unsigned char cfgKeyRegMax;
    unsigned char cfgSecRegMax;
};

struct _FLOATING_SAVE_AREA {
    unsigned short ControlWord;
    unsigned short StatusWord;
    unsigned short TagWord;
    unsigned short ErrorOpcode;
    unsigned long ErrorOffset;
    unsigned long ErrorSelector;
    unsigned long DataOffset;
    unsigned long DataSelector;
    unsigned long MXCsr;
    unsigned long Reserved2;
    unsigned char RegisterArea[128];
    unsigned char XmmRegisterArea[128];
    unsigned char Reserved4[224];
    unsigned long Cr0NpxState;
};

struct _CONTEXT {
    unsigned long ContextFlags;
    struct _FLOATING_SAVE_AREA FloatSave;
    unsigned long Edi;
    unsigned long Esi;
    unsigned long Ebx;
    unsigned long Edx;
    unsigned long Ecx;
    unsigned long Eax;
    unsigned long Ebp;
    unsigned long Eip;
    unsigned long SegCs;
    unsigned long EFlags;
    unsigned long Esp;
    unsigned long SegSs;
};

struct _D3DBOX {
    unsigned int Left;
    unsigned int Top;
    unsigned int Right;
    unsigned int Bottom;
    unsigned int Front;
    unsigned int Back;
};

struct _D3DCAPS8 {
    enum _D3DDEVTYPE DeviceType;
    unsigned int AdapterOrdinal;
    unsigned long Caps;
    unsigned long Caps2;
    unsigned long Caps3;
    unsigned long PresentationIntervals;
    unsigned long CursorCaps;
    unsigned long DevCaps;
    unsigned long PrimitiveMiscCaps;
    unsigned long RasterCaps;
    unsigned long ZCmpCaps;
    unsigned long SrcBlendCaps;
    unsigned long DestBlendCaps;
    unsigned long AlphaCmpCaps;
    unsigned long ShadeCaps;
    unsigned long TextureCaps;
    unsigned long TextureFilterCaps;
    unsigned long CubeTextureFilterCaps;
    unsigned long VolumeTextureFilterCaps;
    unsigned long TextureAddressCaps;
    unsigned long VolumeTextureAddressCaps;
    unsigned long LineCaps;
    unsigned long MaxTextureWidth;
    unsigned long MaxTextureHeight;
    unsigned long MaxVolumeExtent;
    unsigned long MaxTextureRepeat;
    unsigned long MaxTextureAspectRatio;
    unsigned long MaxAnisotropy;
    float MaxVertexW;
    float GuardBandLeft;
    float GuardBandTop;
    float GuardBandRight;
    float GuardBandBottom;
    float ExtentsAdjust;
    unsigned long StencilCaps;
    unsigned long FVFCaps;
    unsigned long TextureOpCaps;
    unsigned long MaxTextureBlendStages;
    unsigned long MaxSimultaneousTextures;
    unsigned long VertexProcessingCaps;
    unsigned long MaxActiveLights;
    unsigned long MaxUserClipPlanes;
    unsigned long MaxVertexBlendMatrices;
    unsigned long MaxVertexBlendMatrixIndex;
    float MaxPointSize;
    unsigned long MaxPrimitiveCount;
    unsigned long MaxVertexIndex;
    unsigned long MaxStreams;
    unsigned long MaxStreamStride;
    unsigned long VertexShaderVersion;
    unsigned long MaxVertexShaderConst;
    unsigned long PixelShaderVersion;
    float MaxPixelShaderValue;
};

struct _D3DLOCKED_BOX {
    int RowPitch;
    int SlicePitch;
    void *pBits;
};

struct _D3DLOCKED_RECT {
    int Pitch;
    void *pBits;
};

struct _D3DMATRIX {
    union {
        struct {
            float _11;
            float _12;
            float _13;
            float _14;
            float _21;
            float _22;
            float _23;
            float _24;
            float _31;
            float _32;
            float _33;
            float _34;
            float _41;
            float _42;
            float _43;
            float _44;
        };
        float m[4][4];
    };
};

struct _D3DPRESENT_PARAMETERS_ {
    unsigned int BackBufferWidth;
    unsigned int BackBufferHeight;
    enum _D3DFORMAT BackBufferFormat;
    unsigned int BackBufferCount;
    unsigned long MultiSampleType;
    enum _D3DSWAPEFFECT SwapEffect;
    struct HWND__ *hDeviceWindow;
    int Windowed;
    int EnableAutoDepthStencil;
    enum _D3DFORMAT AutoDepthStencilFormat;
    unsigned long Flags;
    unsigned int FullScreen_RefreshRateInHz;
    unsigned int FullScreen_PresentationInterval;
};

struct _D3DPixelShaderDef {
    unsigned long PSAlphaInputs[8];
    unsigned long PSFinalCombinerInputsABCD;
    unsigned long PSFinalCombinerInputsEFG;
    unsigned long PSConstant0[8];
    unsigned long PSConstant1[8];
    unsigned long PSAlphaOutputs[8];
    unsigned long PSRGBInputs[8];
    unsigned long PSCompareMode;
    unsigned long PSFinalCombinerConstant0;
    unsigned long PSFinalCombinerConstant1;
    unsigned long PSRGBOutputs[8];
    unsigned long PSCombinerCount;
    unsigned long PSTextureModes;
    unsigned long PSDotMapping;
    unsigned long PSInputTexture;
    unsigned long PSC0Mapping;
    unsigned long PSC1Mapping;
    unsigned long PSFinalCombinerConstants;
};

struct _D3DRECT {
    long x1;
    long y1;
    long x2;
    long y2;
};

struct _D3DSURFACE_DESC {
    enum _D3DFORMAT Format;
    enum _D3DRESOURCETYPE Type;
    unsigned long Usage;
    unsigned int Size;
    unsigned long MultiSampleType;
    unsigned int Width;
    unsigned int Height;
};

struct _D3DVIEWPORT8 {
    unsigned long X;
    unsigned long Y;
    unsigned long Width;
    unsigned long Height;
    float MinZ;
    float MaxZ;
};

struct _DSBUFFERDESC {
    unsigned long dwSize;
    unsigned long dwFlags;
    unsigned long dwBufferBytes;
    struct tWAVEFORMATEX *lpwfxFormat;
    unsigned long dwMixBinMask;
    unsigned long dwInputMixBinMask;
};

struct _DSCAPS {
    unsigned long dwFree2DBuffers;
    unsigned long dwFree3DBuffers;
    unsigned long dwFreeBufferSGEs;
    unsigned long dwMemoryAllocated;
};

struct _DSEFFECTIMAGELOC {
    unsigned long dwI3DL2ReverbIndex;
    unsigned long dwCrosstalkIndex;
};

struct _DSI3DL2OBSTRUCTION {
    long lHFLevel;
    float flLFRatio;
};

struct _DSI3DL2OCCLUSION {
    long lHFLevel;
    float flLFRatio;
};

struct _DSI3DL2BUFFER {
    long lDirect;
    long lDirectHF;
    long lRoom;
    long lRoomHF;
    float flRoomRolloffFactor;
    struct _DSI3DL2OBSTRUCTION Obstruction;
    struct _DSI3DL2OCCLUSION Occlusion;
};

struct _DSI3DL2LISTENER {
    long lRoom;
    long lRoomHF;
    float flRoomRolloffFactor;
    float flDecayTime;
    float flDecayHFRatio;
    long lReflections;
    float flReflectionsDelay;
    long lReverb;
    float flReverbDelay;
    float flDiffusion;
    float flDensity;
    float flHFReference;
};

struct _DSSTREAMDESC {
    unsigned long dwFlags;
    unsigned long dwMaxAttachedPackets;
    struct tWAVEFORMATEX *lpwfxFormat;
    void (__stdcall *lpfnCallback)(void *, void *, unsigned long);
    void *lpvContext;
    unsigned long dwMixBinMask;
};

struct _EXCEPTION_POINTERS {
    struct _EXCEPTION_RECORD *ExceptionRecord;
    struct _CONTEXT *ContextRecord;
};

struct _FILETIME {
    unsigned long dwLowDateTime;
    unsigned long dwHighDateTime;
};

union _LARGE_INTEGER {
    struct {
        unsigned long LowPart;
        long HighPart;
    };
    struct {
        unsigned long LowPart;
        long HighPart;
    } u;
    __int64 QuadPart;
};

struct _LAUNCH_DATA {
    unsigned char Data[3072];
};

struct _LD_LAUNCH_DASHBOARD {
    unsigned long dwReason;
    unsigned long dwContext;
    unsigned long dwParameter1;
    unsigned long dwParameter2;
    unsigned char Reserved[3056];
};

struct _LIST_ENTRY {
    struct _LIST_ENTRY *Flink;
    struct _LIST_ENTRY *Blink;
};

struct _MEMORYSTATUS {
    unsigned long dwLength;
    unsigned long dwMemoryLoad;
    unsigned long dwTotalPhys;
    unsigned long dwAvailPhys;
    unsigned long dwTotalPageFile;
    unsigned long dwAvailPageFile;
    unsigned long dwTotalVirtual;
    unsigned long dwAvailVirtual;
};

struct _OVERLAPPED {
    unsigned long Internal;
    unsigned long InternalHigh;
    unsigned long Offset;
    unsigned long OffsetHigh;
    void *hEvent;
};

struct _RTL_CRITICAL_SECTION {
    union {
        struct {
            unsigned char Type;
            unsigned char Absolute;
            unsigned char Size;
            unsigned char Inserted;
            long SignalState;
            struct _LIST_ENTRY WaitListHead;
        } Event;
        unsigned long RawEvent[4];
    } Synchronization;
    long LockCount;
    long RecursionCount;
    void *OwningThread;
};

struct _SYSTEMTIME {
    unsigned short wYear;
    unsigned short wMonth;
    unsigned short wDayOfWeek;
    unsigned short wDay;
    unsigned short wHour;
    unsigned short wMinute;
    unsigned short wSecond;
    unsigned short wMilliseconds;
};

union _ULARGE_INTEGER {
    struct {
        unsigned long LowPart;
        unsigned long HighPart;
    };
    struct {
        unsigned long LowPart;
        unsigned long HighPart;
    } u;
    unsigned __int64 QuadPart;
};

struct _WIN32_FILE_ATTRIBUTE_DATA {
    unsigned long dwFileAttributes;
    struct _FILETIME ftCreationTime;
    struct _FILETIME ftLastAccessTime;
    struct _FILETIME ftLastWriteTime;
    unsigned long nFileSizeHigh;
    unsigned long nFileSizeLow;
};

struct _WIN32_FIND_DATAA {
    unsigned long dwFileAttributes;
    struct _FILETIME ftCreationTime;
    struct _FILETIME ftLastAccessTime;
    struct _FILETIME ftLastWriteTime;
    unsigned long nFileSizeHigh;
    unsigned long nFileSizeLow;
    unsigned long dwReserved0;
    unsigned long dwReserved1;
    char cFileName[260];
    char cAlternateFileName[14];
};

struct _XCALCSIG_SIGNATURE {
    unsigned char Signature[20];
};

struct _XDEVICE_PREALLOC_TYPE {
    struct _XPP_DEVICE_TYPE *DeviceType;
    unsigned long dwPreallocCount;
};

struct _XGAME_FIND_DATA {
    struct _WIN32_FIND_DATAA wfd;
    char szSaveGameDirectory[260];
    unsigned short szSaveGameName[128];
};

struct _XINPUT_DEBUG_KEYQUEUE_PARAMETERS {
    unsigned long dwFlags;
    unsigned long dwQueueSize;
    unsigned long dwRepeatDelay;
    unsigned long dwRepeatInterval;
};

struct _XINPUT_DEBUG_KEYSTROKE {
    unsigned char VirtualKey;
    char Ascii;
    unsigned char Flags;
};

#pragma pack(push, 2)
struct _XINPUT_FEEDBACK_HEADER {
    unsigned long dwStatus;
    void *hEvent;
    unsigned char Reserved[58];
};
#pragma pack(pop)

struct _XINPUT_RUMBLE {
    unsigned short wLeftMotorSpeed;
    unsigned short wRightMotorSpeed;
};

#pragma pack(push, 2)
struct _XINPUT_FEEDBACK {
    struct _XINPUT_FEEDBACK_HEADER Header;
    struct _XINPUT_RUMBLE Rumble;
};
#pragma pack(pop)

struct _XINPUT_GAMEPAD {
    unsigned short wButtons;
    unsigned char bAnalogButtons[8];
    short sThumbLX;
    short sThumbLY;
    short sThumbRX;
    short sThumbRY;
};

#pragma pack(push, 2)
struct _XINPUT_STATE {
    unsigned long dwPacketNumber;
    struct _XINPUT_GAMEPAD Gamepad;
};
#pragma pack(pop)

struct _XMEDIAINFO {
    unsigned long dwFlags;
    unsigned long dwInputSize;
    unsigned long dwOutputSize;
    unsigned long dwMaxLookahead;
};

struct _XMEDIAPACKET {
    void *pvBuffer;
    unsigned long dwMaxSize;
    unsigned long *pdwCompletedSize;
    unsigned long *pdwStatus;
    union {
        void *hCompletionEvent;
        void *pContext;
    };
    __int64 *prtTimestamp;
};

struct _XPP_DEVICE_TYPE {
    unsigned long Reserved[3];
};

struct fd_set {
    unsigned int fd_count;
    unsigned int fd_array[FD_SETSIZE];
};

struct sockaddr {
    unsigned short sa_family;
    char sa_data[14];
};

struct sockaddr_in {
    short sin_family;
    unsigned short sin_port;
    struct in_addr sin_addr;
    char sin_zero[8];
};

#pragma pack(push, 2)
struct tWAVEFORMATEX {
    unsigned short wFormatTag;
    unsigned short nChannels;
    unsigned long nSamplesPerSec;
    unsigned long nAvgBytesPerSec;
    unsigned short nBlockAlign;
    unsigned short wBitsPerSample;
    unsigned short cbSize;
};
#pragma pack(pop)

struct tagRECT {
    long left;
    long top;
    long right;
    long bottom;
};

struct timeval {
    long tv_sec;
    long tv_usec;
};

#pragma pack(push, 2)
struct xbox_adpcmwaveformat_tag {
    struct tWAVEFORMATEX wfx;
    unsigned short wSamplesPerBlock;
};
#pragma pack(pop)

/* ---------- types */

typedef int BOOL;
typedef unsigned char BYTE;
typedef char CHAR;
typedef struct _CONTEXT CONTEXT;
typedef unsigned long D3DBACKBUFFER_TYPE;
typedef struct _D3DBOX D3DBOX;
typedef struct D3DBaseTexture D3DBaseTexture;
typedef void (*D3DCALLBACK)(unsigned long);
typedef enum _D3DCALLBACKTYPE D3DCALLBACKTYPE;
typedef struct _D3DCAPS8 D3DCAPS8;
typedef unsigned long D3DCOLOR;
typedef enum _D3DCUBEMAP_FACES D3DCUBEMAP_FACES;
typedef struct D3DCubeTexture D3DCubeTexture;
typedef enum _D3DDEVTYPE D3DDEVTYPE;
typedef struct D3DDevice D3DDevice;
typedef enum _D3DFORMAT D3DFORMAT;
typedef struct D3DIndexBuffer D3DIndexBuffer;
typedef struct _D3DLOCKED_BOX D3DLOCKED_BOX;
typedef struct _D3DLOCKED_RECT D3DLOCKED_RECT;
typedef struct _D3DMATRIX D3DMATRIX;
typedef enum _D3DPALETTESIZE D3DPALETTESIZE;
typedef struct _D3DPixelShaderDef D3DPIXELSHADERDEF;
typedef unsigned long D3DPOOL;
typedef struct _D3DPRESENT_PARAMETERS_ D3DPRESENT_PARAMETERS;
typedef enum _D3DPRIMITIVETYPE D3DPRIMITIVETYPE;
typedef struct D3DPalette D3DPalette;
typedef struct _D3DRECT D3DRECT;
typedef enum _D3DRENDERSTATETYPE D3DRENDERSTATETYPE;
typedef struct D3DResource D3DResource;
typedef unsigned long D3DSHADERCONSTANTMODE;
typedef struct _D3DSURFACE_DESC D3DSURFACE_DESC;
typedef struct D3DSurface D3DSurface;
typedef enum _D3DTEXTURESTAGESTATETYPE D3DTEXTURESTAGESTATETYPE;
typedef enum _D3DTRANSFORMSTATETYPE D3DTRANSFORMSTATETYPE;
typedef struct D3DTexture D3DTexture;
typedef struct _D3DVIEWPORT8 D3DVIEWPORT8;
typedef struct D3DVertexBuffer D3DVertexBuffer;
typedef struct D3DVolumeTexture D3DVolumeTexture;
typedef struct _D3DMATRIX D3DXMATRIX;
typedef struct D3DXVECTOR4 D3DXVECTOR4;
typedef struct _DSBUFFERDESC DSBUFFERDESC;
typedef struct _DSCAPS DSCAPS;
typedef struct _DSEFFECTIMAGELOC DSEFFECTIMAGELOC;
typedef struct _DSI3DL2BUFFER DSI3DL2BUFFER;
typedef struct _DSI3DL2LISTENER DSI3DL2LISTENER;
typedef struct _DSSTREAMDESC DSSTREAMDESC;
typedef unsigned long DWORD;
typedef unsigned long DWORD_PTR;
typedef struct Direct3D Direct3D;
typedef struct _FILETIME FILETIME;
typedef float FLOAT;
typedef enum _GET_FILEEX_INFO_LEVELS GET_FILEEX_INFO_LEVELS;
typedef void *HANDLE;
typedef void *HGLOBAL;
typedef struct HINSTANCE__ *HINSTANCE;
typedef void *HLOCAL;
typedef long HRESULT;
typedef struct HWND__ *HWND;
typedef struct IDirectSoundBuffer IDirectSoundBuffer;
typedef struct IDirectSoundStream IDirectSoundStream;
typedef struct IDirectSoundStreamVtbl IDirectSoundStreamVtbl;
typedef int INT;
typedef struct in_addr IN_ADDR;
typedef union _LARGE_INTEGER LARGE_INTEGER;
typedef struct _LAUNCH_DATA LAUNCH_DATA;
typedef long LONG;
typedef __int64 LONGLONG;
typedef const struct _DSBUFFERDESC *LPCDSBUFFERDESC;
typedef const struct _DSEFFECTIMAGELOC *LPCDSEFFECTIMAGELOC;
typedef const struct _DSI3DL2BUFFER *LPCDSI3DL2BUFFER;
typedef const struct _DSI3DL2LISTENER *LPCDSI3DL2LISTENER;
typedef const struct _DSSTREAMDESC *LPCDSSTREAMDESC;
typedef const char *LPCSTR;
typedef const void *LPCVOID;
typedef const unsigned short *LPCWSTR;
typedef const struct _XMEDIAPACKET *LPCXMEDIAPACKET;
typedef struct IDirectSound *LPDIRECTSOUND;
typedef struct IDirectSoundBuffer *LPDIRECTSOUNDBUFFER;
typedef struct IDirectSoundStream *LPDIRECTSOUNDSTREAM;
typedef struct _DSCAPS *LPDSCAPS;
typedef struct _DSEFFECTIMAGEDESC *LPDSEFFECTIMAGEDESC;
typedef unsigned long *LPDWORD;
typedef struct _FILETIME *LPFILETIME;
typedef void (__stdcall *LPFNXMEDIAOBJECTCALLBACK)(void *, void *, unsigned long);
typedef struct _GUID *LPGUID;
typedef long *LPLONG;
typedef struct _MEMORYSTATUS *LPMEMORYSTATUS;
typedef struct _OVERLAPPED *LPOVERLAPPED;
typedef void (__stdcall *LPOVERLAPPED_COMPLETION_ROUTINE)(unsigned long, unsigned long, struct _OVERLAPPED *);
typedef void *LPSECURITY_ATTRIBUTES;
typedef char *LPSTR;
typedef struct _SYSTEMTIME *LPSYSTEMTIME;
typedef unsigned long (__stdcall *LPTHREAD_START_ROUTINE)(void *);
typedef struct IUnknown *LPUNKNOWN;
typedef void *LPVOID;
typedef struct _WIN32_FIND_DATAA *LPWIN32_FIND_DATAA;
typedef struct WSAData *LPWSADATA;
typedef unsigned short *LPWSTR;
typedef struct _XMEDIAINFO *LPXMEDIAINFO;
typedef struct _MEMORYSTATUS MEMORYSTATUS;
typedef struct _OVERLAPPED OVERLAPPED;
typedef unsigned long *PDWORD;
typedef struct _EXCEPTION_POINTERS *PEXCEPTION_POINTERS;
typedef struct _LAUNCH_DATA *PLAUNCH_DATA;
typedef struct _LD_LAUNCH_DASHBOARD *PLD_LAUNCH_DASHBOARD;
typedef long *PLONG;
typedef struct _RTL_CRITICAL_SECTION *PRTL_CRITICAL_SECTION;
typedef union _ULARGE_INTEGER *PULARGE_INTEGER;
typedef struct _XCALCSIG_SIGNATURE *PXCALCSIG_SIGNATURE;
typedef struct _XDEVICE_PREALLOC_TYPE *PXDEVICE_PREALLOC_TYPE;
typedef struct _XGAME_FIND_DATA *PXGAME_FIND_DATA;
typedef struct _XINPUT_DEBUG_KEYQUEUE_PARAMETERS *PXINPUT_DEBUG_KEYQUEUE_PARAMETERS;
typedef struct _XINPUT_DEBUG_KEYSTROKE *PXINPUT_DEBUG_KEYSTROKE;
typedef struct _XINPUT_FEEDBACK *PXINPUT_FEEDBACK;
typedef struct _XINPUT_POLLING_PARAMETERS *PXINPUT_POLLING_PARAMETERS;
typedef struct _XINPUT_STATE *PXINPUT_STATE;
typedef struct _XPP_DEVICE_TYPE *PXPP_DEVICE_TYPE;
typedef struct tagRECT RECT;
typedef struct _RTL_CRITICAL_SECTION RTL_CRITICAL_SECTION;
typedef short SHORT;
typedef unsigned long SIZE_T;
typedef unsigned int SOCKET;
typedef struct _SYSTEMTIME SYSTEMTIME;
typedef unsigned int UINT;
typedef union _ULARGE_INTEGER ULARGE_INTEGER;
typedef unsigned long ULONG;
typedef unsigned __int64 ULONGLONG;
typedef unsigned long ULONG_PTR;
typedef struct tWAVEFORMATEX WAVEFORMATEX;
typedef unsigned short WCHAR;
typedef struct _WIN32_FILE_ATTRIBUTE_DATA WIN32_FILE_ATTRIBUTE_DATA;
typedef struct _WIN32_FIND_DATAA WIN32_FIND_DATAA;
typedef unsigned short WORD;
typedef struct WSAData WSADATA;
typedef struct WSAData WSAData;
typedef struct xbox_adpcmwaveformat_tag XBOXADPCMWAVEFORMAT;
typedef struct _XCALCSIG_SIGNATURE XCALCSIG_SIGNATURE;
typedef struct _XDEVICE_PREALLOC_TYPE XDEVICE_PREALLOC_TYPE;
typedef struct _XGAME_FIND_DATA XGAME_FIND_DATA;
typedef struct _XINPUT_DEBUG_KEYQUEUE_PARAMETERS XINPUT_DEBUG_KEYQUEUE_PARAMETERS;
typedef struct _XINPUT_DEBUG_KEYSTROKE XINPUT_DEBUG_KEYSTROKE;
typedef struct _XINPUT_FEEDBACK XINPUT_FEEDBACK;
typedef struct _XINPUT_GAMEPAD XINPUT_GAMEPAD;
typedef struct _XINPUT_STATE XINPUT_STATE;
typedef struct _XMEDIAPACKET XMEDIAPACKET;
typedef struct XNADDR XNADDR;
typedef struct XNKEY XNKEY;
typedef struct XNKID XNKID;
typedef struct XNetStartupParams XNetStartupParams;
typedef struct _XPP_DEVICE_TYPE XPP_DEVICE_TYPE;
typedef struct _CONTEXT _CONTEXT;
typedef struct _D3DBOX _D3DBOX;
typedef struct _D3DCAPS8 _D3DCAPS8;
typedef struct _D3DLOCKED_BOX _D3DLOCKED_BOX;
typedef struct _D3DLOCKED_RECT _D3DLOCKED_RECT;
typedef struct _D3DMATRIX _D3DMATRIX;
typedef struct _D3DPRESENT_PARAMETERS_ _D3DPRESENT_PARAMETERS_;
typedef struct _D3DPixelShaderDef _D3DPixelShaderDef;
typedef struct _D3DRECT _D3DRECT;
typedef struct _D3DSURFACE_DESC _D3DSURFACE_DESC;
typedef struct _D3DVIEWPORT8 _D3DVIEWPORT8;
typedef struct _DSBUFFERDESC _DSBUFFERDESC;
typedef struct _DSCAPS _DSCAPS;
typedef struct _DSEFFECTIMAGELOC _DSEFFECTIMAGELOC;
typedef struct _DSI3DL2BUFFER _DSI3DL2BUFFER;
typedef struct _DSI3DL2LISTENER _DSI3DL2LISTENER;
typedef struct _DSI3DL2OBSTRUCTION _DSI3DL2OBSTRUCTION;
typedef struct _DSI3DL2OCCLUSION _DSI3DL2OCCLUSION;
typedef struct _DSSTREAMDESC _DSSTREAMDESC;
typedef struct _EXCEPTION_POINTERS _EXCEPTION_POINTERS;
typedef struct _FILETIME _FILETIME;
typedef union _LARGE_INTEGER _LARGE_INTEGER;
typedef struct _LAUNCH_DATA _LAUNCH_DATA;
typedef struct _LD_LAUNCH_DASHBOARD _LD_LAUNCH_DASHBOARD;
typedef struct _MEMORYSTATUS _MEMORYSTATUS;
typedef struct _OVERLAPPED _OVERLAPPED;
typedef struct _SYSTEMTIME _SYSTEMTIME;
typedef union _ULARGE_INTEGER _ULARGE_INTEGER;
typedef struct _WIN32_FILE_ATTRIBUTE_DATA _WIN32_FILE_ATTRIBUTE_DATA;
typedef struct _WIN32_FIND_DATAA _WIN32_FIND_DATAA;
typedef struct _XCALCSIG_SIGNATURE _XCALCSIG_SIGNATURE;
typedef struct _XGAME_FIND_DATA _XGAME_FIND_DATA;
typedef struct _XINPUT_DEBUG_KEYQUEUE_PARAMETERS _XINPUT_DEBUG_KEYQUEUE_PARAMETERS;
typedef struct _XINPUT_DEBUG_KEYSTROKE _XINPUT_DEBUG_KEYSTROKE;
typedef struct _XINPUT_FEEDBACK _XINPUT_FEEDBACK;
typedef struct _XINPUT_FEEDBACK_HEADER _XINPUT_FEEDBACK_HEADER;
typedef struct _XINPUT_GAMEPAD _XINPUT_GAMEPAD;
typedef struct _XINPUT_RUMBLE _XINPUT_RUMBLE;
typedef struct _XINPUT_STATE _XINPUT_STATE;
typedef struct _XMEDIAINFO _XMEDIAINFO;
typedef struct _XMEDIAPACKET _XMEDIAPACKET;
typedef unsigned char boolean;
typedef unsigned char byte;
typedef struct fd_set fd_set;
typedef struct in_addr in_addr;
typedef struct sockaddr sockaddr;
typedef struct sockaddr_in sockaddr_in;
typedef struct tWAVEFORMATEX tWAVEFORMATEX;
typedef struct tagRECT tagRECT;
typedef struct timeval timeval;
typedef unsigned int u_int;
typedef unsigned long u_long;
typedef unsigned short u_short;
typedef struct xbox_adpcmwaveformat_tag xbox_adpcmwaveformat_tag;

/* ---------- data */


/* ---------- functions */

int __stdcall CloseHandle(void *);
long __stdcall CompareFileTime(const struct _FILETIME *, const struct _FILETIME *);
int __stdcall CopyFileA(const char *, const char *, int);
int __stdcall CreateDirectoryA(const char *, void *);
void *__stdcall CreateEventA(void *, int, int, const char *);
void *__stdcall CreateFileA(const char *, unsigned long, unsigned long, void *, unsigned long, unsigned long, void *);
void *__stdcall CreateMutexA(void *, int, const char *);
void *__stdcall CreateThread(void *, unsigned long, unsigned long (__stdcall *)(void *), void *, unsigned long, unsigned long *);
void __stdcall D3DCubeTexture_LockRect(struct D3DCubeTexture *, enum _D3DCUBEMAP_FACES, unsigned int, struct _D3DLOCKED_RECT *, const struct tagRECT *, unsigned long);
void __stdcall D3DDevice_Begin(enum _D3DPRIMITIVETYPE);
void __stdcall D3DDevice_BeginVisibilityTest(void);
void __stdcall D3DDevice_BlockUntilVerticalBlank(void);
void __stdcall D3DDevice_Clear(unsigned long, const struct _D3DRECT *, unsigned long, unsigned long, float, unsigned long);
long __stdcall D3DDevice_CreateCubeTexture(unsigned int, unsigned int, unsigned long, enum _D3DFORMAT, unsigned long, struct D3DCubeTexture **);
long __stdcall D3DDevice_CreateIndexBuffer(unsigned int, unsigned long, enum _D3DFORMAT, unsigned long, struct D3DIndexBuffer **);
long __stdcall D3DDevice_CreatePalette(enum _D3DPALETTESIZE, struct D3DPalette **);
long __stdcall D3DDevice_CreateTexture(unsigned int, unsigned int, unsigned int, unsigned long, enum _D3DFORMAT, unsigned long, struct D3DTexture **);
long __stdcall D3DDevice_CreateVertexBuffer(unsigned int, unsigned long, unsigned long, unsigned long, struct D3DVertexBuffer **);
long __stdcall D3DDevice_CreateVertexShader(const unsigned long *, const unsigned long *, unsigned long *, unsigned long);
long __stdcall D3DDevice_CreateVolumeTexture(unsigned int, unsigned int, unsigned int, unsigned int, unsigned long, enum _D3DFORMAT, unsigned long, struct D3DVolumeTexture **);
void __stdcall D3DDevice_DeleteVertexShader(unsigned long);
void __stdcall D3DDevice_DrawIndexedVertices(enum _D3DPRIMITIVETYPE, unsigned int, const unsigned short *);
void __stdcall D3DDevice_DrawVertices(enum _D3DPRIMITIVETYPE, unsigned int, unsigned int);
void __stdcall D3DDevice_End(void);
long __stdcall D3DDevice_EndVisibilityTest(unsigned long);
void __stdcall D3DDevice_GetBackBuffer(int, unsigned long, struct D3DSurface **);
long __stdcall D3DDevice_GetDepthStencilSurface(struct D3DSurface **);
void __stdcall D3DDevice_GetDeviceCaps(struct _D3DCAPS8 *);
void __stdcall D3DDevice_GetTransform(enum _D3DTRANSFORMSTATETYPE, struct _D3DMATRIX *);
void __stdcall D3DDevice_GetVertexShaderSize(unsigned long, unsigned int *);
long __stdcall D3DDevice_GetVisibilityTestResult(unsigned long, unsigned int *, unsigned __int64 *);
void __stdcall D3DDevice_InsertCallback(enum _D3DCALLBACKTYPE, void (*)(unsigned long), unsigned long);
int __stdcall D3DDevice_IsBusy(void);
void __stdcall D3DDevice_KickPushBuffer(void);
void __stdcall D3DDevice_LoadVertexShader(unsigned long, unsigned long);
long __stdcall D3DDevice_PersistDisplay(void);
void __stdcall D3DDevice_Present(const struct tagRECT *, const struct tagRECT *, void *, void *);
unsigned long __stdcall D3DDevice_Release(void);
void __stdcall D3DDevice_SelectVertexShader(unsigned long, unsigned long);
void __stdcall D3DDevice_SetFlickerFilter(unsigned long);
void __stdcall D3DDevice_SetIndices(struct D3DIndexBuffer *, unsigned int);
void __stdcall D3DDevice_SetPalette(unsigned long, struct D3DPalette *);
void __stdcall D3DDevice_SetPixelShaderProgram(struct _D3DPixelShaderDef *);
void __stdcall D3DDevice_SetRenderStateNotInline(enum _D3DRENDERSTATETYPE, unsigned long);
void __stdcall D3DDevice_SetRenderState_BackFillMode(unsigned long);
void __stdcall D3DDevice_SetRenderState_CullMode(unsigned long);
void __fastcall D3DDevice_SetRenderState_Deferred(enum _D3DRENDERSTATETYPE, unsigned long);
void __stdcall D3DDevice_SetRenderState_DoNotCullUncompressed(unsigned long);
void __stdcall D3DDevice_SetRenderState_Dxt1NoiseEnable(unsigned long);
void __stdcall D3DDevice_SetRenderState_EdgeAntiAlias(unsigned long);
void __stdcall D3DDevice_SetRenderState_FillMode(unsigned long);
void __stdcall D3DDevice_SetRenderState_FogColor(unsigned long);
void __stdcall D3DDevice_SetRenderState_FrontFace(unsigned long);
void __stdcall D3DDevice_SetRenderState_LineWidth(unsigned long);
void __stdcall D3DDevice_SetRenderState_LogicOp(unsigned long);
void __stdcall D3DDevice_SetRenderState_MultiSampleAntiAlias(unsigned long);
void __stdcall D3DDevice_SetRenderState_MultiSampleMask(unsigned long);
void __stdcall D3DDevice_SetRenderState_MultiSampleType(unsigned long);
void __stdcall D3DDevice_SetRenderState_NormalizeNormals(unsigned long);
void __stdcall D3DDevice_SetRenderState_OcclusionCullEnable(unsigned long);
void __stdcall D3DDevice_SetRenderState_PSTextureModes(unsigned long);
void __stdcall D3DDevice_SetRenderState_RopZCmpAlwaysRead(unsigned long);
void __stdcall D3DDevice_SetRenderState_RopZRead(unsigned long);
void __stdcall D3DDevice_SetRenderState_ShadowFunc(unsigned long);
void __fastcall D3DDevice_SetRenderState_Simple(unsigned long, unsigned long);
void __stdcall D3DDevice_SetRenderState_StencilCullEnable(unsigned long);
void __stdcall D3DDevice_SetRenderState_StencilEnable(unsigned long);
void __stdcall D3DDevice_SetRenderState_StencilFail(unsigned long);
void __stdcall D3DDevice_SetRenderState_TextureFactor(unsigned long);
void __stdcall D3DDevice_SetRenderState_TwoSidedLighting(unsigned long);
void __stdcall D3DDevice_SetRenderState_VertexBlend(unsigned long);
void __stdcall D3DDevice_SetRenderState_YuvEnable(unsigned long);
void __stdcall D3DDevice_SetRenderState_ZBias(unsigned long);
void __stdcall D3DDevice_SetRenderState_ZEnable(unsigned long);
void __stdcall D3DDevice_SetRenderTarget(struct D3DSurface *, struct D3DSurface *);
void __stdcall D3DDevice_SetShaderConstantMode(unsigned long);
void __stdcall D3DDevice_SetSoftDisplayFilter(int);
void __stdcall D3DDevice_SetStreamSource(unsigned int, struct D3DVertexBuffer *, unsigned int);
void __stdcall D3DDevice_SetTexture(unsigned long, struct D3DBaseTexture *);
void __stdcall D3DDevice_SetTextureState_BorderColor(unsigned long, unsigned long);
void __stdcall D3DDevice_SetTextureState_BumpEnv(unsigned long, enum _D3DTEXTURESTAGESTATETYPE, unsigned long);
void __stdcall D3DDevice_SetTextureState_ColorKeyColor(unsigned long, unsigned long);
void __fastcall D3DDevice_SetTextureState_Deferred(unsigned long, enum _D3DTEXTURESTAGESTATETYPE, unsigned long);
void __stdcall D3DDevice_SetTextureState_TexCoordIndex(unsigned long, unsigned long);
void __stdcall D3DDevice_SetTransform(enum _D3DTRANSFORMSTATETYPE, const struct _D3DMATRIX *);
void __stdcall D3DDevice_SetVertexData2f(int, float, float);
void __stdcall D3DDevice_SetVertexData2s(int, short, short);
void __stdcall D3DDevice_SetVertexData4f(int, float, float, float, float);
void __stdcall D3DDevice_SetVertexData4ub(int, unsigned char, unsigned char, unsigned char, unsigned char);
void __stdcall D3DDevice_SetVertexDataColor(int, unsigned long);
void __stdcall D3DDevice_SetVertexShader(unsigned long);
void __stdcall D3DDevice_SetVertexShaderConstant(int, const void *, unsigned long);
void __stdcall D3DDevice_SetVerticalBlankCallback(void (*)(unsigned long));
void __stdcall D3DDevice_SetViewport(const struct _D3DVIEWPORT8 *);
void __stdcall D3DPalette_Lock(struct D3DPalette *, unsigned long **, unsigned long);
void __stdcall D3DResource_BlockUntilNotBusy(struct D3DResource *);
int __stdcall D3DResource_IsBusy(struct D3DResource *);
void __stdcall D3DResource_Register(struct D3DResource *, void *);
unsigned long __stdcall D3DResource_Release(struct D3DResource *);
void __stdcall D3DSurface_GetDesc(struct D3DSurface *, struct _D3DSURFACE_DESC *);
void __stdcall D3DSurface_LockRect(struct D3DSurface *, struct _D3DLOCKED_RECT *, const struct tagRECT *, unsigned long);
void __stdcall D3DTexture_GetLevelDesc(struct D3DTexture *, unsigned int, struct _D3DSURFACE_DESC *);
long __stdcall D3DTexture_GetSurfaceLevel(struct D3DTexture *, unsigned int, struct D3DSurface **);
void __stdcall D3DTexture_LockRect(struct D3DTexture *, unsigned int, struct _D3DLOCKED_RECT *, const struct tagRECT *, unsigned long);
void __stdcall D3DVertexBuffer_Lock(struct D3DVertexBuffer *, unsigned int, unsigned int, unsigned char **, unsigned long);
void __stdcall D3DVolumeTexture_LockBox(struct D3DVolumeTexture *, unsigned int, struct _D3DLOCKED_BOX *, const struct _D3DBOX *, unsigned long);
D3DXMATRIX *D3DXMatrixIdentity(D3DXMATRIX *);
D3DXMATRIX *__stdcall D3DXMatrixOrthoLH(D3DXMATRIX *, float, float, float, float);
D3DXMATRIX *__stdcall D3DXMatrixPerspectiveLH(D3DXMATRIX *, float, float, float, float);
struct D3DXVECTOR4 *__stdcall D3DXVec4Transform(struct D3DXVECTOR4 *, const struct D3DXVECTOR4 *, const D3DXMATRIX *);
int __stdcall DeleteFileA(const char *);
struct Direct3D *__stdcall Direct3DCreate8(unsigned int);
long __stdcall Direct3D_CreateDevice(unsigned int, enum _D3DDEVTYPE, void *, unsigned long, struct _D3DPRESENT_PARAMETERS_ *, struct D3DDevice **);
void __stdcall Direct3D_SetPushBufferSize(unsigned long, unsigned long);
long __stdcall DirectSoundCreate(struct _GUID *, struct IDirectSound **, struct IUnknown *);
long __stdcall DirectSoundCreateBuffer(const struct _DSBUFFERDESC *, struct IDirectSoundBuffer **);
void __stdcall DirectSoundDoWork(void);
void __stdcall DirectSoundUseFullHRTF(void);
void *__stdcall FindFirstFileA(const char *, struct _WIN32_FIND_DATAA *);
int __stdcall FindNextFileA(void *, struct _WIN32_FIND_DATAA *);
int __stdcall GetDiskFreeSpaceExA(const char *, union _ULARGE_INTEGER *, union _ULARGE_INTEGER *, union _ULARGE_INTEGER *);
int __stdcall GetExitCodeThread(void *, unsigned long *);
unsigned long __stdcall GetFileAttributesA(const char *);
int __stdcall GetFileAttributesExA(const char *, enum _GET_FILEEX_INFO_LEVELS, void *);
unsigned long __stdcall GetFileSize(void *, unsigned long *);
int __stdcall GetFileTime(void *, struct _FILETIME *, struct _FILETIME *, struct _FILETIME *);
unsigned long __stdcall GetLastError(void);
void __stdcall GetSystemTime(struct _SYSTEMTIME *);
unsigned long __stdcall GetTickCount(void);
void *__stdcall GlobalAlloc(unsigned int, unsigned long);
void __stdcall GlobalMemoryStatus(struct _MEMORYSTATUS *);
void *__stdcall GlobalReAlloc(void *, unsigned long, unsigned int);
long __stdcall IDirectSoundBuffer_Play(struct IDirectSoundBuffer *, unsigned long, unsigned long, unsigned long);
unsigned long __stdcall IDirectSoundBuffer_Release(struct IDirectSoundBuffer *);
long __stdcall IDirectSoundBuffer_SetBufferData(struct IDirectSoundBuffer *, void *, unsigned long);
long __stdcall IDirectSoundBuffer_SetCurrentPosition(struct IDirectSoundBuffer *, unsigned long);
long __stdcall IDirectSoundBuffer_SetLoopRegion(struct IDirectSoundBuffer *, unsigned long, unsigned long);
long __stdcall IDirectSoundBuffer_SetPitch(struct IDirectSoundBuffer *, long);
long __stdcall IDirectSoundBuffer_SetVolume(struct IDirectSoundBuffer *, long);
long __stdcall IDirectSoundBuffer_Stop(struct IDirectSoundBuffer *);
long __stdcall IDirectSoundStream_SetConeAngles(struct IDirectSoundStream *, unsigned long, unsigned long, unsigned long);
long __stdcall IDirectSoundStream_SetConeOrientation(struct IDirectSoundStream *, float, float, float, unsigned long);
long __stdcall IDirectSoundStream_SetConeOutsideVolume(struct IDirectSoundStream *, long, unsigned long);
long __stdcall IDirectSoundStream_SetFrequency(struct IDirectSoundStream *, unsigned long);
long __stdcall IDirectSoundStream_SetI3DL2Source(struct IDirectSoundStream *, const struct _DSI3DL2BUFFER *, unsigned long);
long __stdcall IDirectSoundStream_SetMaxDistance(struct IDirectSoundStream *, float, unsigned long);
long __stdcall IDirectSoundStream_SetMinDistance(struct IDirectSoundStream *, float, unsigned long);
long __stdcall IDirectSoundStream_SetMixBinVolumes(struct IDirectSoundStream *, unsigned long, const long *);
long __stdcall IDirectSoundStream_SetMixBins(struct IDirectSoundStream *, unsigned long);
long __stdcall IDirectSoundStream_SetMode(struct IDirectSoundStream *, unsigned long, unsigned long);
long __stdcall IDirectSoundStream_SetPosition(struct IDirectSoundStream *, float, float, float, unsigned long);
long __stdcall IDirectSoundStream_SetVelocity(struct IDirectSoundStream *, float, float, float, unsigned long);
long __stdcall IDirectSoundStream_SetVolume(struct IDirectSoundStream *, long);
long __stdcall IDirectSound_CommitDeferredSettings(struct IDirectSound *);
long __stdcall IDirectSound_CreateSoundBuffer(struct IDirectSound *, const struct _DSBUFFERDESC *, struct IDirectSoundBuffer **, struct IUnknown *);
long __stdcall IDirectSound_CreateSoundStream(struct IDirectSound *, const struct _DSSTREAMDESC *, struct IDirectSoundStream **, struct IUnknown *);
long __stdcall IDirectSound_DownloadEffectsImage(struct IDirectSound *, const void *, unsigned long, const struct _DSEFFECTIMAGELOC *, struct _DSEFFECTIMAGEDESC **);
long __stdcall IDirectSound_GetCaps(struct IDirectSound *, struct _DSCAPS *);
long __stdcall IDirectSound_GetSpeakerConfig(struct IDirectSound *, unsigned long *);
unsigned long __stdcall IDirectSound_Release(struct IDirectSound *);
long __stdcall IDirectSound_SetDistanceFactor(struct IDirectSound *, float, unsigned long);
long __stdcall IDirectSound_SetI3DL2Listener(struct IDirectSound *, const struct _DSI3DL2LISTENER *, unsigned long);
long __stdcall IDirectSound_SetMixBinHeadroom(struct IDirectSound *, unsigned long, unsigned long);
long __stdcall IDirectSound_SetOrientation(struct IDirectSound *, float, float, float, float, float, float, unsigned long);
long __stdcall IDirectSound_SetPosition(struct IDirectSound *, float, float, float, unsigned long);
long __stdcall IDirectSound_SetRolloffFactor(struct IDirectSound *, float, unsigned long);
long __stdcall IDirectSound_SetVelocity(struct IDirectSound *, float, float, float, unsigned long);
void *__stdcall LocalFree(void *);
unsigned long __stdcall LocalSize(void *);
int __stdcall MoveFileA(const char *, const char *);
void __stdcall OutputDebugStringA(const char *);
int __stdcall QueryPerformanceCounter(union _LARGE_INTEGER *);
int __stdcall QueryPerformanceFrequency(union _LARGE_INTEGER *);
int __stdcall ReadFile(void *, void *, unsigned long, unsigned long *, struct _OVERLAPPED *);
int __stdcall ReadFileEx(void *, void *, unsigned long, struct _OVERLAPPED *, void (__stdcall *)(unsigned long, unsigned long, struct _OVERLAPPED *));
int __stdcall ReleaseMutex(void *);
int __stdcall RemoveDirectoryA(const char *);
int __stdcall ResetEvent(void *);
unsigned long __stdcall ResumeThread(void *);
int __stdcall SetEndOfFile(void *);
int __stdcall SetEvent(void *);
int __stdcall SetFileAttributesA(const char *, unsigned long);
unsigned long __stdcall SetFilePointer(void *, long, long *, unsigned long);
int __stdcall SetFileTime(void *, const struct _FILETIME *, const struct _FILETIME *, const struct _FILETIME *);
void __stdcall SetLastError(unsigned long);
int __stdcall SetThreadPriority(void *, int);
void __stdcall Sleep(unsigned long);
unsigned long __stdcall SleepEx(unsigned long, int);
int __stdcall SwitchToThread(void);
int __stdcall SystemTimeToFileTime(const struct _SYSTEMTIME *, struct _FILETIME *);
int __stdcall VirtualProtect(void *, unsigned long, unsigned long, unsigned long *);
int __stdcall WSACleanup(void);
int __stdcall WSAGetLastError(void);
void __stdcall WSASetLastError(int);
int __stdcall WSAStartup(unsigned short, struct WSAData *);
unsigned long __stdcall WaitForSingleObject(void *, unsigned long);
unsigned long __stdcall WaitForSingleObjectEx(void *, unsigned long, int);
int __stdcall WriteFile(void *, const void *, unsigned long, unsigned long *, struct _OVERLAPPED *);
int __stdcall WriteFileEx(void *, const void *, unsigned long, struct _OVERLAPPED *, void (__stdcall *)(unsigned long, unsigned long, struct _OVERLAPPED *));
void *__stdcall XCalculateSignatureBegin(unsigned long);
unsigned long __stdcall XCalculateSignatureEnd(void *, struct _XCALCSIG_SIGNATURE *);
unsigned long __stdcall XCalculateSignatureUpdate(void *, const unsigned char *, unsigned long);
unsigned long __stdcall XCreateSaveGame(const char *, const unsigned short *, unsigned long, unsigned long, char *, unsigned int);
unsigned long __stdcall XDeleteSaveGame(const char *, const unsigned short *);
int __stdcall XFindClose(void *);
void *__stdcall XFindFirstNicknameW(int, unsigned short *, unsigned int);
void *__stdcall XFindFirstSaveGame(const char *, struct _XGAME_FIND_DATA *);
int __stdcall XFindNextSaveGame(void *, struct _XGAME_FIND_DATA *);
int __stdcall XGetDeviceChanges(struct _XPP_DEVICE_TYPE *, unsigned long *, unsigned long *);
unsigned long __stdcall XGetLanguage(void);
unsigned long __stdcall XGetLaunchInfo(unsigned long *, struct _LAUNCH_DATA *);
void __stdcall XInitDevices(unsigned long, struct _XDEVICE_PREALLOC_TYPE *);
void __stdcall XInputClose(void *);
unsigned long __stdcall XInputDebugGetKeystroke(struct _XINPUT_DEBUG_KEYSTROKE *);
unsigned long __stdcall XInputDebugInitKeyboardQueue(struct _XINPUT_DEBUG_KEYQUEUE_PARAMETERS *);
unsigned long __stdcall XInputGetState(void *, struct _XINPUT_STATE *);
void *__stdcall XInputOpen(struct _XPP_DEVICE_TYPE *, unsigned long, unsigned long, struct _XINPUT_POLLING_PARAMETERS *);
unsigned long __stdcall XInputSetState(void *, struct _XINPUT_FEEDBACK *);
unsigned long __stdcall XLaunchNewImageA(const char *, struct _LAUNCH_DATA *);
int __stdcall XNetCleanup(void);
int __stdcall XNetCreateKey(struct XNKID *, struct XNKEY *);
unsigned long __stdcall XNetGetEthernetLinkStatus(void);
unsigned long __stdcall XNetGetTitleXnAddr(struct XNADDR *);
int __stdcall XNetRandom(unsigned char *, unsigned int);
int __stdcall XNetRegisterKey(const struct XNKID *, const struct XNKEY *);
int __stdcall XNetStartup(const struct XNetStartupParams *);
int __stdcall XNetUnregisterKey(const struct XNKID *);
int __stdcall XNetXnAddrToInAddr(const struct XNADDR *, const struct XNKID *, struct in_addr *);
void *__stdcall XPhysicalAlloc(unsigned long, unsigned long, unsigned long, unsigned long);
void __stdcall XPhysicalFree(void *);
void __stdcall XPhysicalProtect(void *, unsigned long, unsigned long);
unsigned long __stdcall XQueryMemoryProtect(void *);
int __stdcall XSetNicknameW(const unsigned short *, int);
int __stdcall __WSAFDIsSet(unsigned int, struct fd_set *);
unsigned int __stdcall accept(unsigned int, struct sockaddr *, int *);
int __stdcall bind(unsigned int, const struct sockaddr *, int);
int __stdcall closesocket(unsigned int);
int __stdcall connect(unsigned int, const struct sockaddr *, int);
int __stdcall getpeername(unsigned int, struct sockaddr *, int *);
int __stdcall getsockname(unsigned int, struct sockaddr *, int *);
int __stdcall getsockopt(unsigned int, int, int, char *, int *);
unsigned long __stdcall htonl(unsigned long);
unsigned short __stdcall htons(unsigned short);
unsigned long __stdcall inet_addr(const char *);
int __stdcall ioctlsocket(unsigned int, long, unsigned long *);
int __stdcall listen(unsigned int, int);
unsigned long __stdcall ntohl(unsigned long);
unsigned short __stdcall ntohs(unsigned short);
int __stdcall recv(unsigned int, char *, int, int);
int __stdcall recvfrom(unsigned int, char *, int, int, struct sockaddr *, int *);
int __stdcall select(int, struct fd_set *, struct fd_set *, struct fd_set *, const struct timeval *);
int __stdcall send(unsigned int, const char *, int, int);
int __stdcall sendto(unsigned int, const char *, int, int, const struct sockaddr *, int);
int __stdcall setsockopt(unsigned int, int, int, const char *, int);
int __stdcall shutdown(unsigned int, int);
unsigned int __stdcall socket(int, int, int);

/* functions the SDK defined inline (see xdk_d3d8.h) */

void __stdcall D3DDevice_SetRenderState(enum _D3DRENDERSTATETYPE, unsigned long);

#endif
